<a href="https://colab.research.google.com/github/varshaelza/Text-Summarization-Categorization/blob/main/BBC_fuzzy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
% cd drive/My\ Drive/BBC Dataset

/content/drive/My Drive/BBC Dataset

In [ ]:
import pandas as pd
import numpy as np
traindata = pd.read_csv('/content/drive/MyDrive/BBC Dataset/fuzzysampletrain.csv')
testdata = pd.read_csv('/content/drive/MyDrive/BBC Dataset/fuzzysampletest.csv')

In [ ]:
traindata.head()

   Unnamed: 0  ...      Type
0           0  ...      tech
1           1  ...  politics
2           2  ...  business
3           3  ...     sport
4           4  ...     sport

[5 rows x 5 columns]

In [ ]:
def sent_count(text):
  return len(text)

traindata["news_count"]= testdata["sent_token"].apply(lambda text: sent_count(text))

In [ ]:
def sent_count(text):
  return len(text)

traindata["inputsumm_count"]= testdata["Summary"].apply(lambda text: sent_count(text))

In [ ]:
traindata.head()

   Unnamed: 0  ... inputsumm_count
0           0  ...          1242.0
1           1  ...          1079.0
2           2  ...           394.0
3           3  ...           395.0
4           4  ...           805.0

[5 rows x 26 columns]

In [ ]:
testdata.head()

   Unnamed: 0  ...      Type
0        1288  ...  politics
1        1170  ...  politics
2        1388  ...     sport
3        1109  ...  politics
4        1851  ...      tech

[5 rows x 5 columns]

Preprocessing

In [ ]:
#sentence tokenisation

import nltk, csv
nltk.download('punkt')
from nltk import sent_tokenize



#with open('fuzzytrain.csv', 'r') as file:
    #reader = csv.reader(file, delimiter = '\t')
    #data = csv.DictReader(file) 
    #for row in data:
      #sentences=(sent_tokenize(row["News"]))
traindata["sent_token"] = traindata["News"].apply(lambda text: sent_tokenize(text))
traindata["input_summ_token"] = traindata["Summary"].apply(lambda text: sent_tokenize(text))
#traindata.head()
def count(text):
  return len(text)

traindata["sent_token_count"]= traindata["sent_token"].apply(lambda text: count(text))

traindata["input_summary_count"]= traindata["input_summ_token"].apply(lambda text: count(text))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
testdata["sent_token"] = testdata["News"].apply(lambda text: sent_tokenize(text))

In [ ]:
traindata.head()

   Unnamed: 0  ... input_summary_count
0           0  ...                   7
1           1  ...                   1
2           2  ...                   2
3           3  ...                   2
4           4  ...                   1

[5 rows x 29 columns]

In [ ]:
testdata.head()

   Unnamed: 0  ...                                         sent_token
0        1288  ...  [Labour battle plan 'hides Blair'\n \n The Tor...
1        1170  ...  [Tutu's Guantanamo release call\n \n Archbisho...
2        1388  ...  [Holmes starts 2005 with GB events\n \n Kelly ...
3        1109  ...  [Tory expert denies defeatism\n \n The Conserv...
4        1851  ...  [Movie body targets children's PCs\n \n The bo...

[5 rows x 6 columns]

In [ ]:
#stopwords removal
nltk.download('stopwords')
from nltk.corpus import stopwords
from string import punctuation
STOPWORDS = set(stopwords.words('english'))
def rem_stopwords(text):
    return " ".join([word.lower() for word in str(text).split(" ") if word not in STOPWORDS and word not in punctuation and not word.isdigit()])

traindata["no_stopwords"] = traindata["sent_token"].apply(lambda text: rem_stopwords(text))
#traindata.head()

"""
for u in range(len(sentences)):
        sent_split1=[w.lower() for w in sentences[u].split(" ")]
        sent_split=[w for w in sent_split1 if w not in stop_words and w not in punctuation and not w.isdigit()]
"""

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

'\nfor u in range(len(sentences)):\n        sent_split1=[w.lower() for w in sentences[u].split(" ")]\n        sent_split=[w for w in sent_split1 if w not in stop_words and w not in punctuation and not w.isdigit()]\n'

In [ ]:
traindata.head()

   Unnamed: 0  ...                                       no_stopwords
0           0  ...  ['online games play politics\n \n after bubbli...
1           1  ...  ["hague 'given up' pm ambition\n \n former con...
2           2  ...  ['m&s cuts prices average 24%\n \n marks spenc...
3           3  ...  ["zambia confident cautious\n \n zambia's tech...
4           4  ...  ["federer joins all-time greats\n \n the last ...

[5 rows x 7 columns]

In [ ]:
testdata["no_stopwords"] = testdata["sent_token"].apply(lambda text: rem_stopwords(text))
testdata.head()

   Unnamed: 0  ...                                       no_stopwords
0        1288  ...  ['labour battle plan \'hides blair\'\n \n the ...
1        1170  ...  ["tutu's guantanamo release call\n \n archbish...
2        1388  ...  ['holmes starts gb events\n \n kelly holmes st...
3        1109  ...  ["tory expert denies defeatism\n \n the conser...
4        1851  ...  ["movie body targets children's pcs\n \n the b...

[5 rows x 7 columns]

Feature Extraction

In [ ]:
#bigrams
from nltk.util import ngrams

nltk.download('stopwords')
from nltk.corpus import stopwords
from string import punctuation
stop_words = set(stopwords.words('english'))
#bigrams = ngrams(token,2)
def bi_grams(text):
  bi_token=[]
  bi_token_length=[]
  #print(len(text))
  for u in range(len(text)):
    sent_split=[w.lower() for w in text[u].split(" ")]
    sent_split1=[w for w in sent_split if w not in stop_words and w not in punctuation and not w.isdigit()]
    #bigrams_list=list(nltk.bigrams(sent_split1))
    bigrams_list = list(ngrams(sent_split, 2)) 
    #print(bigrams_list)
    #bigrams_list = ngrams(sent_split1,2)
    #bigrams_list = [bigram for bigram in nltk.bigrams(sent_split1)]
    #print(bigrams_list)
    bi_token.append(bigrams_list)
    bi_token_length.append(len(bi_token[u]))
  #print(bi_token_length)
  bi_tokens = [(int(m) / max(bi_token_length))*100 for m in bi_token_length]
  return bi_token_length
      

traindata["bi_grams"] = traindata["sent_token"].apply(lambda text: bi_grams(text))
#traindata.head()

"""
def sent_count(text):
  return len(text)
traindata["bi_count"]= traindata["bi_grams"].apply(lambda text: sent_count(text))

"""

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

'\ndef sent_count(text):\n  return len(text)\ntraindata["bi_count"]= traindata["bi_grams"].apply(lambda text: sent_count(text))\n\n'

In [ ]:
traindata.head()

   Unnamed: 0  ...                                           bi_grams
0           0  ...  [21, 23, 15, 24, 29, 16, 18, 39, 32, 18, 10, 2...
1           1  ...  [29, 19, 20, 20, 22, 20, 12, 1, 20, 25, 13, 18...
2           2  ...  [31, 23, 12, 17, 15, 23, 11, 28, 30, 27, 28, 2...
3           3  ...  [25, 7, 9, 22, 13, 15, 32, 25, 19, 18, 20, 23,...
4           4  ...  [21, 18, 26, 15, 22, 12, 11, 26, 11, 17, 24, 3...

[5 rows x 8 columns]

In [ ]:
testdata["bi_grams"] = testdata["sent_token"].apply(lambda text: bi_grams(text))
testdata.head()

   Unnamed: 0  ...                                           bi_grams
0        1288  ...  [29, 18, 15, 14, 12, 16, 48, 17, 25, 16, 31, 1...
1        1170  ...  [28, 20, 11, 14, 14, 36, 26, 24, 11, 20, 22, 1...
2        1388  ...                       [18, 21, 24, 10, 12, 33, 18]
3        1109  ...                    [26, 26, 20, 13, 9, 10, 24, 24]
4        1851  ...  [30, 19, 14, 9, 11, 28, 15, 31, 11, 39, 20, 28...

[5 rows x 8 columns]

In [ ]:
print(traindata[['bi_grams']])

                                               bi_grams
0     [21, 23, 15, 24, 29, 16, 18, 39, 32, 18, 10, 2...
1     [29, 19, 20, 20, 22, 20, 12, 1, 20, 25, 13, 18...
2     [31, 23, 12, 17, 15, 23, 11, 28, 30, 27, 28, 2...
3     [25, 7, 9, 22, 13, 15, 32, 25, 19, 18, 20, 23,...
4     [21, 18, 26, 15, 22, 12, 11, 26, 11, 17, 24, 3...
...                                                 ...
1775  [21, 16, 12, 16, 20, 20, 31, 31, 17, 18, 41, 1...
1776  [25, 23, 10, 18, 25, 19, 18, 67, 32, 27, 12, 2...
1777  [19, 29, 10, 21, 27, 32, 13, 4, 29, 16, 18, 33...
1778  [21, 13, 22, 18, 25, 23, 23, 9, 5, 10, 3, 14, ...
1779           [25, 23, 18, 16, 39, 24, 14, 32, 19, 26]

[1780 rows x 1 columns]

In [ ]:
"""
def tri_grams(text):
  tri_token=[]
  tri_token_length=[]
  trigrams_list = [trigram for trigram in nltk.trigrams(text)]
  tri_token.append(trigrams_list)
  tri_token_length.append(len(tri_token))
  #print(tri_token_length)
  return tri_token_length
  
      #bi_tokens = [(int(o) / max(bi_token_length))*100 for o in bi_token_length]
      #print("bitokens feature vector:",(bi_token_length))

traindata["tri_grams"] = traindata["no_stopwords"].apply(lambda text: tri_grams(text))
#traindata.head()
def sent_count(text):
  return len(text)

traindata["tri_count"]= traindata["tri_grams"].apply(lambda text: sent_count(text))
"""
import nltk
from nltk.util import ngrams

nltk.download('stopwords')
from nltk.corpus import stopwords
from string import punctuation
stop_words = set(stopwords.words('english'))
#bigrams = ngrams(token,2)


def tri_grams(text):
  tri_token=[]
  tri_token_length=[]
  #print(len(text))
  for u in range(len(text)):
    sent_split2=[w.lower() for w in text[u].split(" ")]
    sent_split3=[w for w in sent_split2 if w not in stop_words and w not in punctuation and not w.isdigit()]
    #print(sent_split2)
    #trigrams_list=list(nltk.trigrams(sent_split3))
    #trigrams_list = list(ngrams((sent_split3),3))
    try :
      trigrams_list = list(ngrams((sent_split3),3))
    except:
       print("Error is :",sent_split3)
    #print(trigrams_list)
    #trigrams_list = extract_ngrams(sent_split2, 3)
    #print(trigrams_list)
    #trigrams_list = ngrams(sent_split2,3)
    #bigrams_list = [bigram for bigram in nltk.bigrams(sent_split2)]
    #print(bigrams_list)
    tri_token.append(trigrams_list)
    #print(len(tri_token[u]))
    l=len(tri_token[u])
    tri_token_length.append(l)
  #print("_____")
  #print(tri_token_length)
  tri_tokens = [(int(m) / max(tri_token_length))*100 for m in tri_token_length]
  return tri_token_length
      

traindata["tri_grams"] = traindata["sent_token"].apply(lambda text: tri_grams(text))
#traindata.head()

"""
def sent_count(text):
  return len(text)
traindata["tri_count"]= traindata["tri_grams"].apply(lambda text: sent_count(text))

"""

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Error is : ['asked.']
Error is : ['brebner.']
Error is : ['up?']
Error is : ['bit.']
Error is : ['said.']
Error is : ['outplayed.']
Error is : ['twice.']
Error is : ['bosvelt.']
Error is : ['possible."']
Error is : ['growing.']
Error is : ['ipod?']
Error is : ['gps?']
Error is : ['competition.']
Error is : ['why?']
Error is : ['shock.']
Error is : ['happen?']
Error is : ['friends.']
Error is : ['me."']
Error is : ['interested."']
Error is : ['can."']
Error is : ['worrying."']
Error is : ['asked.']
Error is : []
Error is : []
Error is : ['djs.']
Error is : ['conceived.']
Error is : ['public.']
Error is : ['not?"']
Error is : ['said.']
Error is : ['said.']
Error is : ['added.']
Error is : ['saying?']
Error is : ['overall.']
Error is : ['that.']
Error is : ['time.']
Error is : ['work?']
Error is : ['polite.']
Error is : ['gps?']
Error is : ['competition.']
Error is : ['why?']
Error is : ['cole.']
Error is : ['20,170.']
Error is : ['9,033.']
Error is : ['delighted."']
Error is : ['said.']
Error is : ['"ditto."']
Error is : ['asked.']
Error is : ['congratulations!']
Error is : ['potential.']
Error is : ['confronted."']
Error is : []
Error is : ['oscar?']
Error is : ['dinosaur."']
Error is : ['perfection!']
Error is : ['maybe.']
Error is : ['rubbish!']
Error is : ['joke!']
Error is : ["'orrible."]
Error is : ['joke.']
Error is : ['chance.']
Error is : ['nope.']
Error is : ['yes!!']
Error is : ['really?']
Error is : ['no?']
Error is : ['sigh.']
Error is : ['britpop?']
Error is : ['"no.']
Error is : ['badly."']
Error is : ['mean?']
Error is : ['morgan.']
Error is : ['personality.']
Error is : ['bit.']
Error is : ['see."']
Error is : ['refuse.']
Error is : ['easy.']
Error is : ['fun!']
Error is : ['lol']
Error is : ['hill.']
Error is : ['said.']
Error is : ['asked.']
Error is : ['said.']
Error is : ['cole.']
Error is : ['not.']
Error is : ['said.']
Error is : ['veritas?']
Error is : ['whitewashed.']
Error is : ['longer.']
Error is : ['blessing."']
Error is : ['"ditto."']
Error is : ['well."']
Error is : ['said.']
Error is : ['said.']
Error is : ['kerrang!']
Error is : ['outrage!']
Error is : ['ambitious.']
Error is : ['truth."']
Error is : ['mccurry']
Error is : ['dramatic.']
Error is : ['worried?']
Error is : ['mistake.']
Error is : ['past."']
Error is : ['reaction?']
Error is : ['what?']
Error is : ['war.']
Error is : ['did.']
Error is : ['agree.']
Error is : ['end.']
Error is : ['i.']
Error is : ['true.']
Error is : ['opinions.']
Error is : ['jakamoko!']
Error is : ['toto!']
Error is : ['joked.']
Error is : ['s.t.a.l.k.e.r.']
Error is : ['entertainment.']
Error is : ['scam.']
Error is : ['veritas?']
Error is : ['clown.']
Error is : ['veritas?']
Error is : ['theory.']
Error is : ['solutions.']
Error is : ['france.']
Error is : ['fighting."']

'\ndef sent_count(text):\n  return len(text)\ntraindata["tri_count"]= traindata["tri_grams"].apply(lambda text: sent_count(text))\n\n'

In [ ]:
traindata.head()

   Unnamed: 0  ...                                          tri_grams
0           0  ...  [12, 11, 8, 15, 16, 8, 10, 24, 16, 7, 5, 11, 1...
1           1  ...  [17, 11, 8, 11, 13, 9, 7, 0, 11, 15, 5, 9, 6, ...
2           2  ...  [17, 13, 7, 11, 8, 14, 6, 18, 17, 17, 12, 13, ...
3           3  ...     [16, 4, 3, 7, 4, 7, 14, 11, 8, 8, 8, 12, 5, 6]
4           4  ...  [16, 12, 14, 11, 13, 5, 4, 13, 5, 8, 11, 19, 1...

[5 rows x 9 columns]

In [ ]:
testdata["tri_grams"] = testdata["sent_token"].apply(lambda text: tri_grams(text))
testdata.head()

Error is : ['asks.']
Error is : ['why?']
Error is : ['tool.']
Error is : ['hope.']
Error is : ['improve."']
Error is : ['recalled.']
Error is : ['djs.']
Error is : ['added.']
Error is : ['terrible."']
Error is : ['exceptions.']
Error is : ['said.']
Error is : ['43,856.']
Error is : ['james.']
Error is : ['pity.']
Error is : ['theory.']
Error is : ['solutions.']
Error is : ['strange.']
Error is : ['nonsense.']
Error is : ['talented.']
Error is : ['kamara.']
Error is : ['says.']
Error is : ['untrue.']
Error is : ['thundercats!!']
Error is : ['care!']
Error is : ['asks.']
Error is : ['confronted."']

   Unnamed: 0  ...                                          tri_grams
0        1288  ...  [17, 9, 9, 9, 7, 12, 24, 8, 14, 10, 17, 5, 15,...
1        1170  ...  [18, 10, 7, 8, 9, 17, 15, 13, 4, 7, 12, 5, 1, ...
2        1388  ...                          [9, 15, 13, 5, 5, 15, 10]
3        1109  ...                       [18, 14, 7, 6, 7, 7, 14, 10]
4        1851  ...  [18, 14, 5, 3, 5, 19, 6, 17, 7, 24, 13, 14, 14...

[5 rows x 9 columns]

In [ ]:


def position(text):
  
  return [index for index, value in enumerate(text)]


traindata["sent_position"] = traindata["sent_token"].apply(lambda text: position(text))

def sent_count(text):
  return len(text)
  
#sent_position= (position(sentences))
#num_sent=len(sent_position)
traindata["num_of_sent"]= traindata["sent_position"].apply(lambda text: sent_count(text))

"""
      position = []
      position_rbm = []
      sent_pos1_rbm = 1
      sent_pos1 = 100
      position.append(sent_pos1)
      position_rbm.append(sent_pos1_rbm)
      for x in range(1,num_sent-1):
          s_p= ((num_sent-x)/num_sent)*100
          position.append(s_p)
          s_p_rbm = (num_sent-x)/num_sent
          position_rbm.append(s_p_rbm)
    
      sent_pos2 = 100
      sent_pos2_rbm = 1
      position.append(sent_pos2)
      position_rbm.append(sent_pos2_rbm)
      print("Sentence position feature vector:",position_rbm)
      print("\n")

"""

def pos_vec(text):
  position = []
  position_rbm = []
  sent_pos1_rbm = 1
  sent_pos1 = 100
  sent_pos2 = 100
  sent_pos2_rbm = 1
  position.append(sent_pos1)
  position_rbm.append(sent_pos1_rbm)
  for x in range(1,text-1):
    s_p=((text-x)/text)*100
    position.append(s_p)
    s_p_rbm=(text-x)/text
    position_rbm.append(s_p_rbm)
  position.append(sent_pos2)
  position_rbm.append(sent_pos2_rbm)
  return position_rbm

traindata["sent_pos_vec"]= traindata["num_of_sent"].apply(lambda text: pos_vec(text))
"""
def sent_count(text):
  return len(text)

traindata["sp_count"]= traindata["sent_pos_vec"].apply(lambda text: sent_count(text))

"""

'\ndef sent_count(text):\n  return len(text)\n\ntraindata["sp_count"]= traindata["sent_pos_vec"].apply(lambda text: sent_count(text))\n\n'

In [ ]:
traindata.head()

   Unnamed: 0  ...                                       sent_pos_vec
0           0  ...  [1, 0.9583333333333334, 0.9166666666666666, 0....
1           1  ...  [1, 0.9333333333333333, 0.8666666666666667, 0....
2           2  ...  [1, 0.9333333333333333, 0.8666666666666667, 0....
3           3  ...  [1, 0.9285714285714286, 0.8571428571428571, 0....
4           4  ...  [1, 0.9666666666666667, 0.9333333333333333, 0....

[5 rows x 12 columns]

In [ ]:
testdata["sent_position"] = testdata["sent_token"].apply(lambda text: position(text))
testdata["num_of_sent"]= testdata["sent_position"].apply(lambda text: sent_count(text))
testdata["sent_pos_vec"]= testdata["num_of_sent"].apply(lambda text: pos_vec(text))
testdata.head()

   Unnamed: 0  ...                                       sent_pos_vec
0        1288  ...  [1, 0.96, 0.92, 0.88, 0.84, 0.8, 0.76, 0.72, 0...
1        1170  ...  [1, 0.9545454545454546, 0.9090909090909091, 0....
2        1388  ...  [1, 0.8571428571428571, 0.7142857142857143, 0....
3        1109  ...       [1, 0.875, 0.75, 0.625, 0.5, 0.375, 0.25, 1]
4        1851  ...  [1, 0.9411764705882353, 0.8823529411764706, 0....

[5 rows x 12 columns]

In [ ]:
#sentences to vectors

"""
def convertToVSM(sentences):
        vocabulary = []
        for sents in sentences:
            vocabulary.extend(sents)
        vocabulary = list(set(vocabulary))
        vectors = []
        for sents in sentences:
            vector = []
            for tokenss in vocabulary:
                vector.append(sents.count(tokenss))
            vectors.append(vector)
        return vectors
      VSM=convertToVSM(sentences)
      print("SentenceVectors:",VSM)
      print("\n")
"""
def sent_to_vector(text):
  vocabulary = []
  for sents in text:
    vocabulary.extend(sents)
  vocabulary = list(set(vocabulary))
  vectors = []
  for sents in text:
    vector = []
    for tokenss in vocabulary:
      vector.append(sents.count(tokenss))
    vectors.append(vector)
  return vectors

traindata["sent_vec"]= traindata["sent_token"].apply(lambda text: sent_to_vector(text))
"""
def sent_count(text):
  return len(text)

traindata["sentvec_count"]= traindata["sent_vec"].apply(lambda text: sent_count(text))
"""

'\ndef sent_count(text):\n  return len(text)\n\ntraindata["sentvec_count"]= traindata["sent_vec"].apply(lambda text: sent_count(text))\n'

In [ ]:
traindata.head()

   Unnamed: 0  ...                                           sent_vec
0           0  ...  [[0, 0, 10, 4, 1, 0, 0, 21, 1, 0, 4, 0, 0, 0, ...
1           1  ...  [[5, 0, 18, 6, 1, 0, 29, 1, 0, 6, 1, 0, 0, 0, ...
2           2  ...  [[3, 0, 2, 7, 2, 2, 0, 0, 31, 1, 0, 3, 0, 1, 0...
3           3  ...  [[0, 0, 12, 2, 1, 0, 0, 25, 1, 0, 4, 0, 1, 12,...
4           4  ...  [[0, 5, 6, 0, 0, 0, 21, 1, 0, 3, 0, 0, 0, 0, 0...

[5 rows x 13 columns]

In [ ]:
testdata["sent_vec"]= testdata["sent_token"].apply(lambda text: sent_to_vector(text))
testdata.head()

   Unnamed: 0  ...                                           sent_vec
0        1288  ...  [[2, 2, 14, 0, 0, 0, 29, 0, 6, 0, 2, 8, 0, 11,...
1        1170  ...  [[0, 0, 8, 5, 1, 0, 28, 0, 7, 0, 0, 0, 11, 0, ...
2        1388  ...  [[1, 0, 7, 2, 1, 18, 0, 2, 0, 2, 0, 3, 5, 9, 0...
3        1109  ...  [[2, 0, 11, 3, 26, 0, 6, 0, 0, 0, 0, 11, 1, 12...
4        1851  ...  [[3, 0, 12, 5, 0, 0, 30, 1, 0, 6, 1, 0, 0, 9, ...

[5 rows x 13 columns]

In [ ]:
traindata[['sent_vec']]

                                               sent_vec
0     [[0, 0, 10, 4, 1, 0, 0, 21, 1, 0, 4, 0, 0, 0, ...
1     [[5, 0, 18, 6, 1, 0, 29, 1, 0, 6, 1, 0, 0, 0, ...
2     [[3, 0, 2, 7, 2, 2, 0, 0, 31, 1, 0, 3, 0, 1, 0...
3     [[0, 0, 12, 2, 1, 0, 0, 25, 1, 0, 4, 0, 1, 12,...
4     [[0, 5, 6, 0, 0, 0, 21, 1, 0, 3, 0, 0, 0, 0, 0...
...                                                 ...
1775  [[1, 0, 1, 10, 1, 0, 0, 21, 0, 1, 0, 0, 0, 0, ...
1776  [[0, 0, 9, 2, 0, 0, 25, 0, 6, 1, 0, 0, 0, 1, 1...
1777  [[1, 0, 4, 3, 0, 0, 0, 19, 0, 0, 0, 4, 2, 0, 0...
1778  [[2, 0, 5, 2, 0, 0, 21, 0, 6, 2, 0, 9, 0, 9, 9...
1779  [[0, 0, 12, 2, 0, 25, 0, 0, 10, 0, 0, 6, 0, 6,...

[1780 rows x 1 columns]

In [ ]:
!sudo pip install nltk==3.4

Collecting nltk==3.4
  Downloading https://files.pythonhosted.org/packages/6f/ed/9c755d357d33bc1931e157f537721efb5b88d2c583fe593cc09603076cc3/nltk-3.4.zip (1.4MB)
     |████████████████████████████████| 1.4MB 5.1MB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from nltk==3.4) (1.15.0)
Collecting singledispatch
  Downloading https://files.pythonhosted.org/packages/7a/12/2b10635e91ec4007e2a287812b1a1c8649cf68686ff2d69ed97553cf8a7a/singledispatch-3.6.1-py2.py3-none-any.whl
Building wheels for collected packages: nltk
  Building wheel for nltk (setup.py) ... done
  Created wheel for nltk: filename=nltk-3.4-cp37-none-any.whl size=1436382 sha256=9f4df1b959ca2e64142b90de1aba28c8ffd2a58ee20e560d5f4bb4575f01422a
  Stored in directory: /root/.cache/pip/wheels/4b/c8/24/b2343664bcceb7147efeb21c0b23703a05b23fcfeaceaa2a1e
Successfully built nltk
Installing collected packages: singledispatch, nltk
  Found existing installation: nltk 3.2.5
    Uninstalling nltk-3.2.5:
      Successfully uninstalled nltk-3.2.5
Successfully installed nltk-3.4 singledispatch-3.6.1

In [ ]:
#tf-isf and centroid 
""" 
  #sentencelength=len(sentences)
  def calcMeanTF_ISF(text, index):
    vocab_len = len(text[index])
    sentences_len = len(text)
    count = 0
    tfisf = 0
    for i in range(vocab_len):
      tf = text[index][i]
      if(tf>0):
        count += 1
        sent_freq = 0
        for j in range(sentences_len):
          if(VSM[j][i]>0): sent_freq += 1
        tfisf += (tf)*(1.0/sent_freq)
    if(count > 0):
      mean_tfisf = tfisf/count
    else:
      mean_tfisf = 0
  return tf, (1.0/sent_freq), mean_tfisf
  tfvec=[]
  isfvec=[]
  tfisfvec=[]
  tfisfvec_rbm=[]
  for i in range(len(text)):
    x,y,z=calcMeanTF_ISF(text[i],i)
    tfvec.append(x)
    isfvec.append(y)
    tfisfvec.append(z*100)
    tfisfvec_rbm.append(z)
      #print("TF vector:",tfvec)
      #print("\n")
      #print("ISF vector:",isfvec)
      #print("\n")
      #tfisf1= [(int(p)*100) for p in tfisfvec]
  print("TF-ISF vector:",tfisfvec_rbm)
  print("\n")
  maxtf_isf=max(tfisfvec_rbm)
  centroid=[]
  centroid.append(maxtf_isf)
  print("Max TF-ISF:",centroid)
  print("\n")
      
  centroid=(max(VSM))
  print("Centroid:",centroid)
  print("\n")

"""

  

def tfisf(text):
  tfvec=[]
  isfvec=[]
  tfisfvec=[]
  tfisfvec_rbm=[]
  for i in range(len(text)):
    vocab_len = len(text[i])
    sentences_len = len(text)
    count = 0
    tfisf = 0
    for j in range(vocab_len):
      tf = text[i][j]
      if(tf>0):
        count += 1
        sent_freq = 0
        for k in range(sentences_len):
          if(text[k][j]>0): sent_freq += 1
        tfisf += (tf)*(1.0/sent_freq)
    if(count > 0):
      mean_tfisf = tfisf/count
    else:
      mean_tfisf = 0
    x,y,z= tf, (1.0/sent_freq), mean_tfisf
    tfvec.append(x)
    isfvec.append(y)
    tfisfvec.append(z*100)
    tfisfvec_rbm.append(z)

  return tfisfvec_rbm


traindata["tfisf"]= traindata["sent_vec"].apply(lambda text: tfisf(text))
"""
def sent_count(text):
  return len(text)

traindata["tfisf_count"]= traindata["tfisf"].apply(lambda text: sent_count(text))
"""

'\ndef sent_count(text):\n  return len(text)\n\ntraindata["tfisf_count"]= traindata["tfisf"].apply(lambda text: sent_count(text))\n'

In [ ]:
traindata.head()

   Unnamed: 0  ...                                              tfisf
0           0  ...  [0.35842179961745174, 0.28776726206850434, 0.2...
1           1  ...  [0.5324234904880067, 0.3396969696969697, 0.371...
2           2  ...  [0.5780167748917748, 0.4173462737978866, 0.202...
3           3  ...  [0.5426390108208288, 0.2532301032301032, 0.216...
4           4  ...  [0.2566840754316461, 0.1931480280802941, 0.181...

[5 rows x 14 columns]

In [ ]:
testdata["tfisf"]= testdata["sent_vec"].apply(lambda text: tfisf(text))
testdata.head()

   Unnamed: 0  ...                                              tfisf
0        1288  ...  [0.3596857390485576, 0.20002276038507924, 0.16...
1        1170  ...  [0.4075697913059341, 0.22073569577869542, 0.20...
2        1388  ...  [0.8275641025641025, 0.8534562211981566, 0.927...
3        1109  ...  [0.8908866995073891, 0.7858294930875575, 0.642...
4        1851  ...  [0.4386866945690474, 0.4077661793884221, 0.229...

[5 rows x 14 columns]

In [ ]:
#max tfisf
def max_tfisf(text):
  maxtf_isf=max(text)
  centroid=[]
  centroid.append(maxtf_isf)
  return centroid

traindata["max_tfisf"]= traindata["tfisf"].apply(lambda text: max_tfisf(text))

In [ ]:
traindata.head()

   Unnamed: 0  ...              max_tfisf
0           0  ...   [0.4282645281686202]
1           1  ...   [0.5324234904880067]
2           2  ...   [0.5780167748917748]
3           3  ...   [0.5458160119450441]
4           4  ...  [0.27296986575202936]

[5 rows x 15 columns]

In [ ]:
testdata["max_tfisf"]= testdata["tfisf"].apply(lambda text: max_tfisf(text))
testdata.head()

   Unnamed: 0  ...              max_tfisf
0        1288  ...  [0.46811862689739925]
1        1170  ...   [0.4443290050270506]
2        1388  ...   [1.0796031746031747]
3        1109  ...   [0.8908866995073891]
4        1851  ...   [0.5687424845868868]

[5 rows x 15 columns]

In [ ]:
#centroid
def centroid(text):
  centroid=(max(text))
  return centroid

traindata["centroid"]= traindata["sent_vec"].apply(lambda text: centroid(text))
traindata.head()

   Unnamed: 0  ...                                           centroid
0           0  ...  [3, 2, 15, 5, 0, 0, 0, 39, 4, 1, 11, 0, 1, 0, ...
1           1  ...  [5, 0, 18, 6, 1, 0, 29, 1, 0, 6, 1, 0, 0, 0, 1...
2           2  ...  [3, 0, 2, 7, 2, 2, 0, 0, 31, 1, 0, 3, 0, 1, 0,...
3           3  ...  [2, 0, 8, 3, 0, 0, 0, 25, 0, 0, 8, 0, 0, 7, 1,...
4           4  ...  [4, 14, 3, 0, 0, 1, 26, 3, 1, 5, 0, 1, 0, 0, 0...

[5 rows x 16 columns]

In [ ]:
testdata["centroid"]= testdata["sent_vec"].apply(lambda text: centroid(text))
testdata.head()

   Unnamed: 0  ...                                           centroid
0        1288  ...  [3, 0, 14, 5, 0, 0, 28, 1, 5, 0, 1, 9, 0, 12, ...
1        1170  ...  [5, 2, 13, 1, 0, 0, 36, 0, 11, 0, 0, 0, 12, 0,...
2        1388  ...  [4, 2, 5, 6, 0, 33, 0, 10, 0, 0, 0, 7, 9, 8, 1...
3        1109  ...  [4, 2, 4, 1, 20, 0, 5, 0, 0, 0, 0, 8, 1, 9, 5,...
4        1851  ...  [5, 2, 10, 2, 0, 0, 28, 1, 0, 8, 0, 0, 0, 9, 0...

[5 rows x 16 columns]

In [ ]:
#cosine-similarity between centroids and sentences
from numpy import dot
from numpy.linalg import norm

def centroid(text):
  centroid=(max(text))
  return centroid
def cos_sim(text):
  cent=centroid(text)
  cosine_similarity=[]
  cosine_similarity_rbm=[]
  for z in range(len(text)):
    cos_simi = ((dot(cent, text[z])/(norm(cent)*norm(text[z])))*100)
    cosine_similarity.append(cos_simi)
    cos_simi_rbm = (dot(cent, text[z])/(norm(cent)*norm(text[z])))
    cosine_similarity_rbm.append(cos_simi_rbm)
 #     print("Cosine Similarity Vector:",cosine_similarity_rbm)
#    print("\n")
  return cosine_similarity_rbm

traindata["cos_sim"]= traindata["sent_vec"].apply(lambda text: cos_sim(text))
traindata.head()

   Unnamed: 0  ...                                            cos_sim
0           0  ...  [0.9480231555983256, 0.9797108125317912, 0.966...
1           1  ...  [1.0, 0.9139581764625258, 0.8777861281040995, ...
2           2  ...  [0.9999999999999999, 0.9202908168657439, 0.917...
3           3  ...  [0.8780864479701957, 0.8532917370223534, 0.939...
4           4  ...  [0.9411325676595443, 0.9480229940289965, 0.945...

[5 rows x 17 columns]

In [ ]:
testdata["cos_sim"]= testdata["sent_vec"].apply(lambda text: cos_sim(text))
testdata.head()

   Unnamed: 0  ...                                            cos_sim
0        1288  ...  [0.9663689384296827, 0.9496236586631162, 0.944...
1        1170  ...  [0.9557653370746226, 0.940216578528482, 0.9318...
2        1388  ...  [0.8758302745458754, 0.8477997829845644, 0.881...
3        1109  ...  [0.9100132498824068, 0.9346570903868451, 1.0, ...
4        1851  ...  [0.976797660549434, 0.9138996286348587, 0.9119...

[5 rows x 17 columns]

In [ ]:
#sentence length feature

def sentencelen(text):
  sent_word=[]
  for u in range(len(text)):
    sent_split1=[w.lower() for w in text[u].split(" ")]
    sent_split=[w for w in sent_split1 if w not in stop_words and w not in punctuation and not w.isdigit()]
    a=(len(sent_split))
    sent_word.append(a)
  longest_sent=max(sent_word)
  sent_length=[]
  sent_length_rbm=[]
  for x in sent_word:
    sent_length.append((x/longest_sent)*100)
    sent_length_rbm.append(x/longest_sent)
        #print(sent_length)
  return sent_length_rbm

traindata["sent_len"]= traindata["sent_token"].apply(lambda text: sentencelen(text))
traindata.head()

   Unnamed: 0  ...                                           sent_len
0           0  ...  [0.5384615384615384, 0.5, 0.38461538461538464,...
1           1  ...  [1.0, 0.6842105263157895, 0.5263157894736842, ...
2           2  ...  [0.95, 0.75, 0.45, 0.65, 0.5, 0.8, 0.4, 1.0, 0...
3           3  ...  [1.0, 0.3333333333333333, 0.2777777777777778, ...
4           4  ...  [0.782608695652174, 0.6086956521739131, 0.6956...

[5 rows x 18 columns]

In [ ]:
testdata["sent_len"]= testdata["sent_token"].apply(lambda text: sentencelen(text))
testdata.head()

   Unnamed: 0  ...                                           sent_len
0        1288  ...  [0.7307692307692307, 0.4230769230769231, 0.423...
1        1170  ...  [1.0, 0.6, 0.45, 0.5, 0.55, 0.95, 0.85, 0.75, ...
2        1388  ...  [0.6470588235294118, 1.0, 0.8823529411764706, ...
3        1109  ...        [1.0, 0.8, 0.45, 0.4, 0.45, 0.45, 0.8, 0.6]
4        1851  ...  [0.7692307692307693, 0.6153846153846154, 0.269...

[5 rows x 18 columns]

In [ ]:
#numeric token feature
import re
def sentword(text):
  sent_word=[]
  for u in range(len(text)):
      sent_split1=[w.lower() for w in text[u].split(" ")]
      sent_split=[w for w in sent_split1 if w not in stop_words and w not in punctuation and not w.isdigit()]
      a=(len(sent_split))
      sent_word.append(a)
  #print(sent_word)
  return sent_word
def numeric_token(text):
  
  num_word=[]
  numeric_token=[]
  numeric_token_rbm=[]
  sd=sentword(text)
  #print(sd)
  for u in range(len(text)):
    #sd=sentword(text[u])
    
    sent_split4=text[u].split(" ")
    e=re.findall("\d+",text[u])
    noofwords=(len(e))
    num_word.append(noofwords)
    try:
      numeric_token.append((num_word[u]/sd[u])*100)
    except:
      print("Error is:", sd[u])
    try:
      numeric_token_rbm.append(num_word[u]/sd[u])
    except:
      print("Error is:", sd[u]) 
  return numeric_token_rbm

traindata["num_token"]= traindata["sent_token"].apply(lambda text: numeric_token(text))
traindata.head()

Error is: 0
Error is: 0
Error is: 0
Error is: 0
Error is: 0
Error is: 0

   Unnamed: 0  ...                                          num_token
0           0  ...  [0.07142857142857142, 0.0, 0.0, 0.058823529411...
1           1  ...  [0.0, 0.07692307692307693, 0.1, 0.0, 0.0, 0.0,...
2           2  ...  [0.10526315789473684, 0.0, 0.0, 0.0, 0.0, 0.0,...
3           3  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0625, 0.0, 0....
4           4  ...  [0.0, 0.07142857142857142, 0.0, 0.0, 0.0, 0.0,...

[5 rows x 19 columns]

In [ ]:
testdata["num_token"]= testdata["sent_token"].apply(lambda text: numeric_token(text))
testdata.head()

   Unnamed: 0  ...                                          num_token
0        1288  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
1        1170  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
2        1388  ...  [0.18181818181818182, 0.0, 0.06666666666666667...
3        1109  ...         [0.0, 0.125, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
4        1851  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.444...

[5 rows x 19 columns]

In [ ]:
#thematic words feature
! pip install rake-nltk
from rake_nltk import Rake
def thm_word_ftr(text):
      r = Rake() # Uses stopwords for english from NLTK, and all puntuation characters.    *********optimise with our own*********
      keywords=[]
      for s in text:
          r.extract_keywords_from_text(s)
          key=list(r.get_ranked_phrases())
          keywords.append(key)
      #print(keywords)
      l_keywords=[]
      for s in keywords:
          leng=len(s)
          l_keywords.append(leng)
      #print(l_keywords)

      total_keywords=sum(l_keywords)
      #print(total_keywords)

      thematic_number= []
      thematic_number_rbm= []
      for x in l_keywords:
          thematic_number.append((x/total_keywords)*100)
          thematic_number_rbm.append(x/total_keywords)
      #print("Thematic word feature", thematic_number_rbm)
      #print("\n")
      return thematic_number_rbm


traindata["thematic_word"]= traindata["sent_token"].apply(lambda text:thm_word_ftr(text))
traindata.head()

Collecting rake-nltk
  Downloading https://files.pythonhosted.org/packages/8e/c4/b4ff57e541ac5624ad4b20b89c2bafd4e98f29fd83139f3a81858bdb3815/rake_nltk-1.0.4.tar.gz
Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (from rake-nltk) (3.4)
Requirement already satisfied: singledispatch in /usr/local/lib/python3.7/dist-packages (from nltk->rake-nltk) (3.6.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from nltk->rake-nltk) (1.15.0)
Building wheels for collected packages: rake-nltk
  Building wheel for rake-nltk (setup.py) ... done
  Created wheel for rake-nltk: filename=rake_nltk-1.0.4-py2.py3-none-any.whl size=7819 sha256=ce6f0cb4c6604fe3df17ced6b74f597927399eb73dd8be12057c55be8ee83405
  Stored in directory: /root/.cache/pip/wheels/ef/92/fc/271b3709e71a96ffe934b27818946b795ac6b9b8ff8682483f
Successfully built rake-nltk
Installing collected packages: rake-nltk
Successfully installed rake-nltk-1.0.4

   Unnamed: 0  ...                                      thematic_word
0           0  ...  [0.04519774011299435, 0.05084745762711865, 0.0...
1           1  ...  [0.06930693069306931, 0.09900990099009901, 0.0...
2           2  ...  [0.09243697478991597, 0.06722689075630252, 0.0...
3           3  ...  [0.10101010101010101, 0.04040404040404041, 0.0...
4           4  ...  [0.034334763948497854, 0.02145922746781116, 0....

[5 rows x 20 columns]

In [ ]:
testdata["thematic_word"]= testdata["sent_token"].apply(lambda text:thm_word_ftr(text))
testdata.head()

   Unnamed: 0  ...                                      thematic_word
0        1288  ...  [0.05202312138728324, 0.046242774566473986, 0....
1        1170  ...  [0.05714285714285714, 0.03571428571428571, 0.0...
2        1388  ...  [0.11764705882352941, 0.13725490196078433, 0.1...
3        1109  ...  [0.17647058823529413, 0.19607843137254902, 0.1...
4        1851  ...  [0.10317460317460317, 0.06349206349206349, 0.0...

[5 rows x 20 columns]

In [ ]:
nltk.download('averaged_perceptron_tagger')
from nltk.tag import pos_tag
from collections import Counter
def sentword(text):
  sent_word=[]
  for u in range(len(text)):
      sent_split1=[w.lower() for w in text[u].split(" ")]
      sent_split=[w for w in sent_split1 if w not in stop_words and w not in punctuation and not w.isdigit()]
      a=(len(sent_split))
      sent_word.append(a)
  #print(sent_word)
  return sent_word
def pronoun(text):
  pncounts = []
  pncounts_rbm = []
  pnounscore_rbm = []
  sd=sentword(text)
  for sent in text:
    tagged=nltk.pos_tag(nltk.word_tokenize(str(sent)))
    counts = Counter(tag for word,tag in tagged if tag.startswith('NNP') or tag.startswith('NNPS'))
    f=sum(counts.values())
    pncounts.append(f)
    pncounts_rbm.append(f)
  try:
    pnounscore=[(int(o) / int(p))*100 for o,p in zip(pncounts, sd)]
    pnounscore_rbm=[int(o) / int(p) for o,p in zip(pncounts_rbm, sd)]
  except:
    print("Error:",sd)
      #print(pncounts)
      #print("Pronoun feature vector",pnounscore_rbm)
      #print("\n")
  return pnounscore_rbm

traindata["proper_noun"]= traindata["sent_token"].apply(lambda text:pronoun(text))
traindata.head()

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
Error: [20, 8, 13, 10, 3, 0, 0, 4, 9, 10, 9, 9, 8, 13, 9, 14, 6, 5, 6, 9, 5, 10]
Error: [22, 15, 13, 7, 15, 5, 11, 12, 11, 19, 7, 16, 16, 12, 19, 10, 11, 17, 11, 12, 8, 13, 9, 3, 17, 0]

   Unnamed: 0  ...                                        proper_noun
0           0  ...  [0.0, 0.07692307692307693, 0.0, 0.294117647058...
1           1  ...  [0.3157894736842105, 0.3076923076923077, 0.2, ...
2           2  ...  [0.3157894736842105, 0.26666666666666666, 0.44...
3           3  ...  [0.5, 0.16666666666666666, 0.2, 0.0, 0.0, 0.11...
4           4  ...  [0.05555555555555555, 0.42857142857142855, 0.5...

[5 rows x 21 columns]

In [ ]:
testdata["proper_noun"]= testdata["sent_token"].apply(lambda text:pronoun(text))
testdata.head()

   Unnamed: 0  ...                                        proper_noun
0        1288  ...  [0.21052631578947367, 0.09090909090909091, 0.1...
1        1170  ...  [0.4, 0.16666666666666666, 0.0, 0.2, 0.4545454...
2        1388  ...  [0.36363636363636365, 0.35294117647058826, 0.4...
3        1109  ...  [0.2, 0.375, 0.2222222222222222, 0.25, 0.44444...
4        1851  ...  [0.1, 0.4375, 0.0, 0.0, 0.14285714285714285, 0...

[5 rows x 21 columns]

In [ ]:
! pip install -U scikit-fuzzy
import skfuzzy as fuzz
from skfuzzy import control as ctrl

Collecting scikit-fuzzy
  Downloading https://files.pythonhosted.org/packages/6c/f0/5eb5dbe0fd8dfe7d4651a8f4e591a196623a22b9e5339101e559695b4f6c/scikit-fuzzy-0.4.2.tar.gz (993kB)
     |████████████████████████████████| 1.0MB 6.7MB/s
Requirement already satisfied, skipping upgrade: numpy>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from scikit-fuzzy) (1.19.5)
Requirement already satisfied, skipping upgrade: scipy>=0.9.0 in /usr/local/lib/python3.7/dist-packages (from scikit-fuzzy) (1.4.1)
Requirement already satisfied, skipping upgrade: networkx>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from scikit-fuzzy) (2.5.1)
Requirement already satisfied, skipping upgrade: decorator<5,>=4.3 in /usr/local/lib/python3.7/dist-packages (from networkx>=1.9.0->scikit-fuzzy) (4.4.2)
Building wheels for collected packages: scikit-fuzzy
  Building wheel for scikit-fuzzy (setup.py) ... done
  Created wheel for scikit-fuzzy: filename=scikit_fuzzy-0.4.2-cp37-none-any.whl size=894069 sha256=f71b8ba8594a7097683b9bebdf58b614f27e44be3481e807b8e8f6da38c677e9
  Stored in directory: /root/.cache/pip/wheels/b9/4e/77/da79b16f64ef1738d95486e2731eea09d73e90a72465096600
Successfully built scikit-fuzzy
Installing collected packages: scikit-fuzzy
Successfully installed scikit-fuzzy-0.4.2

In [ ]:
      position1 = ctrl.Antecedent(np.arange(0, 100, 10), 'position1')
      cos_similarity = ctrl.Antecedent(np.arange(0, 100, 10), 'cos_similarity')
      bitokens = ctrl.Antecedent(np.arange(0, 100, 10), 'bitokens')
      tritokens = ctrl.Antecedent(np.arange(0, 100, 10), 'tritokens')
      propernoun = ctrl.Antecedent(np.arange(0, 100, 10), 'propernoun')
      sentencelength = ctrl.Antecedent(np.arange(0, 100, 10), 'sentencelength')
      numtokens = ctrl.Antecedent(np.arange(0, 100, 10), 'numtokens')
      keywords = ctrl.Antecedent(np.arange(0, 10, 1), 'keywords')
      tf_isf = ctrl.Antecedent(np.arange(0, 100, 10), 'tf_isf')

      senten = ctrl.Consequent(np.arange(0, 100, 10), 'senten')

NameError: ignored

In [ ]:
      position1.automf(3)
      cos_similarity.automf(3)
      bitokens.automf(3)
      tritokens.automf(3)
      propernoun.automf(3)
      sentencelength.automf(3)
      numtokens.automf(3)
      keywords.automf(3)
      tf_isf.automf(3)

In [ ]:
      senten['bad'] = fuzz.trimf(senten.universe, [0, 0, 50])
      senten['avg'] = fuzz.trimf(senten.universe, [0, 50, 100])
      senten['good'] = fuzz.trimf(senten.universe, [50, 100, 100])

In [ ]:
      rule1 = ctrl.Rule(position1['good'] & sentencelength['good'] & propernoun['good'] &numtokens['good'], senten['good'])
      rule2 = ctrl.Rule(position1['poor'] & sentencelength['poor'] & numtokens['poor'], senten['bad'])
      rule3 = ctrl.Rule(propernoun['poor'] & keywords['average'], senten['bad'])
      rule4 = ctrl.Rule(cos_similarity['good'], senten['good'])
      rule5 = ctrl.Rule(bitokens['good'] & tritokens['good'] & numtokens['average'] | tf_isf['average'], senten['avg'])

In [ ]:
      sent_ctrl = ctrl.ControlSystem([rule1,rule2,rule3,rule4,rule5])
      Sent = ctrl.ControlSystemSimulation(sent_ctrl)

Fuzzy Logic implementation

In [ ]:
    ! pip install -U scikit-fuzzy
    import skfuzzy as fuzz
    from skfuzzy import control as ctrl
    from numpy import dot
    from numpy.linalg import norm

    import re
    ! pip install rake-nltk
    from rake_nltk import Rake

    nltk.download('averaged_perceptron_tagger')
    from nltk.tag import pos_tag
    from collections import Counter


    from nltk.util import ngrams

    nltk.download('stopwords')
    from nltk.corpus import stopwords
    from string import punctuation
    stop_words = set(stopwords.words('english'))
    #bigrams = ngrams(token,2)

    def centroid(text):
      centroid=(max(text))
      return centroid
    def cos_sim1(text):
      cent=centroid(text)
      cosine_similarity=[]
      cosine_similarity_rbm=[]
      for z in range(len(text)):
        cos_simi = ((dot(cent, text[z])/(norm(cent)*norm(text[z])))*100)
        cosine_similarity.append(cos_simi)
        cos_simi_rbm = (dot(cent, text[z])/(norm(cent)*norm(text[z])))
        cosine_similarity_rbm.append(cos_simi_rbm)
    #     print("Cosine Similarity Vector:",cosine_similarity_rbm)
    #    print("\n")
      return cosine_similarity


    def tfisf1(text):
      tfvec=[]
      isfvec=[]
      tfisfvec=[]
      tfisfvec_rbm=[]
      for i in range(len(text)):
        vocab_len = len(text[i])
        sentences_len = len(text)
        count = 0
        tfisf = 0
        for j in range(vocab_len):
          tf = text[i][j]
          if(tf>0):
            count += 1
            sent_freq = 0
            for k in range(sentences_len):
              if(text[k][j]>0): sent_freq += 1
            tfisf += (tf)*(1.0/sent_freq)
        if(count > 0):
          mean_tfisf = tfisf/count
        else:
          mean_tfisf = 0
        x,y,z= tf, (1.0/sent_freq), mean_tfisf
        tfvec.append(x)
        isfvec.append(y)
        tfisfvec.append(z*100)
        tfisfvec_rbm.append(z)

      return tfisfvec

    def vsm_tfisf(text):
      vocabulary = []
      for sents in text:
        vocabulary.extend(sents)
      vocabulary = list(set(vocabulary))
      vectors = []
      for sents in text:
        vector = []
        for tokenss in vocabulary:
          vector.append(sents.count(tokenss))
        vectors.append(vector)
      tfvec=tfisf1(vectors)
      return tfvec

    def vsm_cos(text):
      vocabulary = []
      for sents in text:
        vocabulary.extend(sents)
      vocabulary = list(set(vocabulary))
      vectors = []
      for sents in text:
        vector = []
        for tokenss in vocabulary:
          vector.append(sents.count(tokenss))
        vectors.append(vector)
      cosvec=cos_sim1(vectors)
      return cosvec

    def tri_token(text):
      tri_token=[]
      tri_token_length=[]
      #print(len(text))
      for u in range(len(text)):
        sent_split2=[w.lower() for w in text[u].split(" ")]
        sent_split3=[w for w in sent_split2 if w not in stop_words and w not in punctuation and not w.isdigit()]
        #print(sent_split2)
        #trigrams_list=list(nltk.trigrams(sent_split3))
        #trigrams_list = list(ngrams((sent_split3),3))
        try :
          trigrams_list = list(ngrams((sent_split3),3))
        except:
          print("Error is :",sent_split3)
        #print(trigrams_list)
        #trigrams_list = extract_ngrams(sent_split2, 3)
        #print(trigrams_list)
        #trigrams_list = ngrams(sent_split2,3)
        #bigrams_list = [bigram for bigram in nltk.bigrams(sent_split2)]
        #print(bigrams_list)
        tri_token.append(trigrams_list)
        #print(len(tri_token[u]))
        l=len(tri_token[u])
        tri_token_length.append(l)
      #print("_____")
      #print(tri_token_length)
      tri_tokens = [(int(m) / max(tri_token_length))*100 for m in tri_token_length]
      return tri_tokens


    def bi_token(text):
      bi_token=[]
      bi_token_length=[]
      #print(len(text))
      for u in range(len(text)):
        sent_split=[w.lower() for w in text[u].split(" ")]
        sent_split1=[w for w in sent_split if w not in stop_words and w not in punctuation and not w.isdigit()]
        #bigrams_list=list(nltk.bigrams(sent_split1))
        bigrams_list = list(ngrams(sent_split, 2)) 
        #print(bigrams_list)
        #bigrams_list = ngrams(sent_split1,2)
        #bigrams_list = [bigram for bigram in nltk.bigrams(sent_split1)]
        #print(bigrams_list)
        bi_token.append(bigrams_list)
        bi_token_length.append(len(bi_token[u]))
      #print(bi_token_length)
      bi_tokens = [(int(m) / max(bi_token_length))*100 for m in bi_token_length]
      return bi_tokens


    def sentword(text):
      sent_word=[]
      for u in range(len(text)):
          sent_split1=[w.lower() for w in text[u].split(" ")]
          sent_split=[w for w in sent_split1 if w not in stop_words and w not in punctuation and not w.isdigit()]
          a=(len(sent_split))
          sent_word.append(a)
      #print(sent_word)
      return sent_word

    def pnoun(text):
      pncounts = []
      pncounts_rbm = []
      pnounscore_rbm = []
      pnounscore=[]
      sd=sentword(text)
      for sent in text:
        tagged=nltk.pos_tag(nltk.word_tokenize(str(sent)))
        counts = Counter(tag for word,tag in tagged if tag.startswith('NNP') or tag.startswith('NNPS'))
        f=sum(counts.values())
        pncounts.append(f)
        pncounts_rbm.append(f)
      try:
        pnounscore=[(int(o) / int(p))*100 for o,p in zip(pncounts, sd)]
        pnounscore_rbm=[int(o) / int(p) for o,p in zip(pncounts_rbm, sd)]
      except:
        print("Error:",sd)
          #print(pncounts)
          #print("Pronoun feature vector",pnounscore_rbm)
          #print("\n")
      return pnounscore

    def thm_word(text):
          r = Rake() # Uses stopwords for english from NLTK, and all puntuation characters.    *********optimise with our own*********
          keywords=[]
          for s in text:
              r.extract_keywords_from_text(s)
              key=list(r.get_ranked_phrases())
              keywords.append(key)
          #print(keywords)
          l_keywords=[]
          for s in keywords:
              leng=len(s)
              l_keywords.append(leng)
          #print(l_keywords)

          total_keywords=sum(l_keywords)
          #print(total_keywords)

          thematic_number= []
          thematic_number_rbm= []
          for x in l_keywords:
              thematic_number.append((x/total_keywords)*100)
              thematic_number_rbm.append(x/total_keywords)
          #print("Thematic word feature", thematic_number_rbm)
          #print("\n")
          return thematic_number

    def sentword(text):
      sent_word=[]
      for u in range(len(text)):
          sent_split1=[w.lower() for w in text[u].split(" ")]
          sent_split=[w for w in sent_split1 if w not in stop_words and w not in punctuation and not w.isdigit()]
          a=(len(sent_split))
          sent_word.append(a)
      #print(sent_word)
      return sent_word

    def numtoken(text):
      num_word=[]
      numeric_token=[]
      numeric_token_rbm=[]
      sd=sentword(text)
      #print(sd)
      for u in range(len(text)):
        #sd=sentword(text[u])
        
        sent_split4=text[u].split(" ")
        e=re.findall("\d+",text[u])
        noofwords=(len(e))
        num_word.append(noofwords)
        try:
          numeric_token.append((num_word[u]/sd[u])*100)
        except:
          print("Error is:", sd[u])
        try:
          numeric_token_rbm.append(num_word[u]/sd[u])
        except:
          print("Error is:", sd[u]) 
      return numeric_token


    def sentlen(text):
      sent_word=[]
      for u in range(len(text)):
        sent_split1=[w.lower() for w in text[u].split(" ")]
        sent_split=[w for w in sent_split1 if w not in stop_words and w not in punctuation and not w.isdigit()]
        a=(len(sent_split))
        sent_word.append(a)
      longest_sent=max(sent_word)
      sent_length=[]
      sent_length_rbm=[]
      for x in sent_word:
        sent_length.append((x/longest_sent)*100)
        sent_length_rbm.append(x/longest_sent)
            #print(sent_length)
      return sent_length


    

    def pos_vec1(text):
      position = []
      position_rbm = []
      sent_pos1_rbm = 1
      sent_pos1 = 100
      sent_pos2 = 100
      sent_pos2_rbm = 1
      position.append(sent_pos1)
      position_rbm.append(sent_pos1_rbm)
      for x in range(1,len(text)-1):
        s_p=((len(text)-x)/len(text))*100
        position.append(s_p)
        s_p_rbm=(len(text)-x)/len(text)
        position_rbm.append(s_p_rbm)
      position.append(sent_pos2)
      position_rbm.append(sent_pos2_rbm)
      return position



    def fuzzyimp(text):  
      position1 = ctrl.Antecedent(np.arange(0, 100, 10), 'position1')
      
      cos_similarity = ctrl.Antecedent(np.arange(0, 100, 10), 'cos_similarity')
      bitokens = ctrl.Antecedent(np.arange(0, 100, 10), 'bitokens')
      #print(bitokens)
      tritokens = ctrl.Antecedent(np.arange(0, 100, 10), 'tritokens')

      propernoun = ctrl.Antecedent(np.arange(0, 100, 10), 'propernoun')
      sentencelength = ctrl.Antecedent(np.arange(0, 100, 10), 'sentencelength')
      numtokens = ctrl.Antecedent(np.arange(0, 100, 10), 'numtokens')
      keywords = ctrl.Antecedent(np.arange(0, 10, 1), 'keywords')
      tf_isf = ctrl.Antecedent(np.arange(0, 100, 10), 'tf_isf')

      senten = ctrl.Consequent(np.arange(0, 100, 10), 'senten')
      position1.automf(3)
      cos_similarity.automf(3)
      bitokens.automf(3)
      tritokens.automf(3)
      propernoun.automf(3)
      sentencelength.automf(3)
      numtokens.automf(3)
      keywords.automf(3) 
      tf_isf.automf(3)

      #triagular membership function
      """
      senten['bad'] = fuzz.trimf(senten.universe, [0, 0, 50])
      senten['avg'] = fuzz.trimf(senten.universe, [0, 50, 100])
      senten['good'] = fuzz.trimf(senten.universe, [50, 100, 100])
      """

      #trapezoidal membership function
      senten['bad'] = fuzz.trapmf(senten.universe, [0, 0, 0,50])
      senten['avg'] = fuzz.trapmf(senten.universe, [0, 0, 50, 100])
      senten['good'] = fuzz.trapmf(senten.universe, [0, 50, 100, 100])
      #senten['verygood'] = fuzz.trapmf(senten.universe, [50, 100, 100, 100])

      rule1 = ctrl.Rule(position1['good'] & sentencelength['good'] & propernoun['good'] &numtokens['good'], senten['good'])
      rule2 = ctrl.Rule(position1['poor'] & sentencelength['poor'] & numtokens['poor'], senten['bad'])
      rule3 = ctrl.Rule(propernoun['poor'] & keywords['average'], senten['bad'])
      rule4 = ctrl.Rule(cos_similarity['good'], senten['good'])
      rule5 = ctrl.Rule(bitokens['good'] & tritokens['good'] & numtokens['average'] | tf_isf['average'], senten['avg'])

      sent_ctrl = ctrl.ControlSystem([rule1,rule2,rule3,rule4,rule5])
      Sent = ctrl.ControlSystemSimulation(sent_ctrl)
      fuzzemptyarr= np.empty((100,1,2), dtype=object)
      t2=0
      summary2=[]
      pos=pos_vec1(text)
      cs=vsm_cos(text)
      sl=sentlen(text)
      nt=numtoken(text)
      tw=thm_word(text)
      pn=pnoun(text)
      bi=bi_token(text)
      tri=tri_token(text)
      tf=vsm_tfisf(text)
      for s in range(len(text)):
          try:
            Sent.input['position1'] = int(pos[s])
            Sent.input['cos_similarity'] = int(cs[s])
            Sent.input['bitokens'] = int(bi[s])
            Sent.input['tritokens'] = int(tri[s])
            Sent.input['tf_isf'] = int(tf[s])
            Sent.input['keywords'] = int(tw[s])

            Sent.input['propernoun'] = int(pn[s])
            Sent.input['sentencelength'] = int(sl[s])
            Sent.input['numtokens'] = int(nt[s])
        #Sent.input['service'] = 2
            Sent.compute()
          except:
            print("Error here")
          try:
            if Sent.output['senten'] > 50:
                summary2.append((text[s]))
                try:
                  fuzzemptyarr[t2][0][0] = text[s]
                  fuzzemptyarr[t2][0][1] = s
                  t2+=1
                except:
                  print("Error:",text[s])
          except KeyError:
            print("cant find senten")
      fuzzarray = np.empty((len(summary2),1,2),dtype=object)
      for i in range(len(summary2)):
        try:
          fuzzarray[i][0][0] = fuzzemptyarr[i][0][0]
          fuzzarray[i][0][1] = fuzzemptyarr[i][0][1]
        except:
          print("Error in:")
      fuzzarray=fuzzarray[1:]
      #print("Fuzzy logic summary \n\n",summary2)
      #print(len(summary2))
      return summary2

traindata["summ"]= traindata["sent_token"].apply(lambda text:fuzzyimp(text))
traindata.head()

Requirement already up-to-date: scikit-fuzzy in /usr/local/lib/python3.7/dist-packages (0.4.2)
Requirement already satisfied, skipping upgrade: networkx>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from scikit-fuzzy) (2.5.1)
Requirement already satisfied, skipping upgrade: numpy>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from scikit-fuzzy) (1.19.5)
Requirement already satisfied, skipping upgrade: scipy>=0.9.0 in /usr/local/lib/python3.7/dist-packages (from scikit-fuzzy) (1.4.1)
Requirement already satisfied, skipping upgrade: decorator<5,>=4.3 in /usr/local/lib/python3.7/dist-packages (from networkx>=1.9.0->scikit-fuzzy) (4.4.2)
Requirement already satisfied: rake-nltk in /usr/local/lib/python3.7/dist-packages (1.0.4)
Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (from rake-nltk) (3.4)
Requirement already satisfied: singledispatch in /usr/local/lib/python3.7/dist-packages (from nltk->rake-nltk) (3.6.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from nltk->rake-nltk) (1.15.0)
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Error is : ['asked.']
Error is : ['brebner.']
Error is : ['up?']
Error is : ['bit.']
Error is : ['said.']
Error is : ['outplayed.']
Error is : ['twice.']
Error is : ['bosvelt.']
Error is : ['possible."']
Error is : ['growing.']
Error is : ['ipod?']
Error is : ['gps?']
Error is : ['competition.']
Error is : ['why?']
Error is : ['shock.']
Error is : ['happen?']
Error is : ['friends.']
Error is : ['me."']
Error is : ['interested."']
Error: Seems a good idea and will hopefully be an incentive to those who live to claim to actually get a job.
Error: When you can "earn" more from claiming than you can from work, there is no incentive.
Error: Perhaps a step in the right direction.
Error: If the TUC get their way a very large number of SMEs will have to close - this will put more people out of work.
Error: How then will the government fudge the unemployment figures!
Error: The government know it is not big business that keeps the economy going but the SMEs but we always get overlooked, they will only take notice if these large corporations close and move to other countries, after all they are predominantly owned by foreign companies.
Error: We are a specialist company but with these increases have already had an effect on us and we have lost work another one will close us.
Error: While I'm delighted for those on low pay that this increase is being put forward, I am extremely concerned at the implications for small businesses.
Error: As an employee for a small nursery, I know this increase will cause great hardship for my employer, who has been unable to increase salaries for higher paid employees because of last October's increase for the lower paid employees - who were originally being paid slightly above the minimum but are now on the minimum.
Error: This latest increase of 20p an hour will cause even more financial hardship.
Error: If the rate rises to £6 then I can foresee many small businesses having to pay off employees.
Error: The increase in minimum wage will have a serious effect on my business.
Error: Although we pay above the minimum level we will have to increase our pay rates to maintain the differential.
Error: The raise is well above inflation and without significant increases in sales, it will mean that I will not be taking on a new member of staff as planned and I will be looking to reduce the total hours worked by the other members of staff, overtime being the first to go.
Error: I currently employ 42 staff whose wages mirror the national minimum wage.
Error: Increases above inflation are fine but all of my business is conducted with local authorities who will not accept above inflation rises in my service delivery.
Error: 80% of my costs are labour.
Error: The other aspect that is always hidden is that the thresholds for tax credits do not move in line with these increases so that all that happens is that employees tax credit support is reduced by the amount of the increase, thereby saving the government money but increasing the financial burden on small to medium businesses

 It is very good that the government has decided to increase the minimum wage - this should hopefully motivate people to undertake the "lower status" jobs.
Error: I know about this great idea - don't bother getting qualifications, laze about at school, no need to do anything other than attend so your parents don't get fined because remember, when you do eventually start working, doesn't matter how lazy you are, you'll be guaranteed a decent wage.
Error: I hope that if industry and business have to pay this new rate that Mr Blair and Mr Brown will increase tax allowances and raise national insurance thresholds so that the treasury won't take some of this increase off the people they say they are helping, or is this just another form of stealth tax on business through the back door?
Error: I don't believe in the minimum wage at all!
Error: I think jobs should create their own wage value and that if people want higher wages they should earn them.
Error: Now, before everyone thinks that I am some "rich-kid", I can assure you I am not.
Error: I came from a very much working class background and started work 20 years ago on a Youth Opportunity Program earning £25 per week.
Error: I worked hard, went to college part time, got my A-levels and degree & bettered myself.
Error: I now earn a 6 figure salary.
Error: To Ashley, of Swindon: when you earned £25 per week, it was worth something.
Error: These days that £25 would need to be near to £60 to have the equivalent buying power.
Error: I might add, that thanks to successive governments holding down the tax allowance threshold below inflation, people earning the minimum wage are paying taxes that they never would have done 10 years ago at equivalent wages.
Error: "In my day" type arguments are a view that belong in the 'your day' - 20 years ago!
Error: I disagree with Ashley, Swindon saying I have to work harder to get more pay.
Error: I have my GCSE's A-Levels and A degree and have chosen to work for a small business that can't afford the wages I should be getting, I should be on at least 3x what I'm getting but they can't afford it.
Error: But on the plus side I love my job and wouldn't change it just to get more pay.
Error: As an employer of staff in several shops the last rise in the minimum wage cost my company an additional £5000 per year.
Error: In answer to Emma from Sleaford regarding no one really wins in the end... on the contrary Mr Blair wins - he wins because he obviously has announced this to be a vote winner and his treasury wins because as an employer you will know that the amount of tax and national insurance that the government will receive from all the minimum wage increases will rise and of course not only will be paying out higher wages but as an employer higher Employer NI Contributions as well.
Error: If the minimum wage increases again and if it hits anywhere near the £6.00 mark there will be 12 more people on the employment line and one more small business going bankrupt - namely mine.
Error: Think of us employers as well Mr Blair, we are not all big corporations earning millions.
Error: How many people on the minimum wage have any hope of obtaining a mortgage or saving towards retirement?
Error: Students who do odd jobs can increase their income and can help there family in their home country.
Error: I thank Mr. Blair and his government for increase in the national minimum wage.
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error is : ['can."']
Error is : ['worrying."']
Error is : ['asked.']
Error is: 0
Error is: 0
Error is: 0
Error is: 0
Error: [20, 8, 13, 10, 3, 0, 0, 4, 9, 10, 9, 9, 8, 13, 9, 14, 6, 5, 6, 9, 5, 10]
Error is : []
Error is : []
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error is : ['djs.']
Error is : ['conceived.']
Error is : ['public.']
Error is : ['not?"']
Error is : ['said.']
Error is : ['said.']
Error is : ['added.']
Error is : ['saying?']
Error is : ['overall.']
Error is : ['that.']
Error is : ['time.']
Error is : ['work?']
Error is : ['polite.']
Error is : ['gps?']
Error is : ['competition.']
Error is : ['why?']
Error is : ['cole.']
Error is : ['20,170.']
Error is : ['9,033.']
Error is : ['delighted."']
Error is : ['said.']
Error is : ['"ditto."']
Error is : ['asked.']
Error is : ['congratulations!']
Error is : ['potential.']
Error is : ['confronted."']
Error is: 0
Error is: 0
Error: [22, 15, 13, 7, 15, 5, 11, 12, 11, 19, 7, 16, 16, 12, 19, 10, 11, 17, 11, 12, 8, 13, 9, 3, 17, 0]
Error is : []
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error here
cant find senten
Error is : ['oscar?']
Error is : ['dinosaur."']
Error is : ['perfection!']
Error is : ['maybe.']
Error is : ['rubbish!']
Error is : ['joke!']
Error is : ["'orrible."]
Error is : ['joke.']
Error is : ['chance.']
Error is : ['nope.']
Error is : ['yes!!']
Error is : ['really?']
Error is : ['no?']
Error is : ['sigh.']
Error is : ['britpop?']
Error: I've always disliked Angels intensely.
Error: I believe it to be symbolic of the general capacity of British pre-teens, teens and middle aged women to accept low quality/ low aspirational music as "classic" songwriting.
Error: It seems obvious to me that people who like Robbie are people who don't particularly like music all that much.
Error: Folks without collections; folks who have never engaged in that madness one experiences when falling under the spell of pop music.
Error: Angels adds nothing - it is merely an irritating distraction - a wasp that refuses to go away on a summer's afternoon picnic.
Error: What a dreadful result.
Error: If you voted for it - you should feel ashamed of yourself - you probably only know a dozen songs or so don't you - so where do get off applying this uninformed filter and casting this ridiculous vote.
Error: Booo hisss

 Angels, best song?
Error: You are kidding, right?
Error: Last five years I might be willing to accept, but 25, no way.
Error: Did whoever voted for this actually have ANY music knowledge prior to, say, 1995?
Error: Really quite insulting to the British music industry of the past quarter of a century.
Error: No surprise about Robbie Williams considering the list.
Error: Where on earth did the nominations list come from????
Error: Compiled by an eleven year-old girl perhaps??
Error: I mean, Will Young?
Error: What a load of crap, best song in the last 25 years - I don't think so!!
Error: What about all the REAL artists out there over the last 25 years - the list is endless, but Robbie Williams doesn't even come close.
Error: What a joke.
Error: That song has become such a bane to me that I have developed a Pavlovian response to the word 'Angels' where I thrash around, and scream "no no no no no" until someone tells me "the radio's off".
Error: Why a half-baked cheesy ditty like Angels, which has become the anthem for millions of romantic sops (think how many times it was sung on Pop Idol for example, and by whom), should be voted the best song of the past 25 years, is beyond me.
Error: If this is the song against which all others are judged, then musicians may as well give up.
Error: Why do we reward mediocrity so highly in this country??
Error: The initial list was very weak anyway, but Angels the best song of the last 25 years!!!!
Error: I think not, I didn't realize Radio 2 had so many listeners under the age of 10!!
Error: People have such short memories!
Error: A great song yes, but the best of the last 25 years?
Error: Not a chance.
Error: I think the person as opposed to the song has been voted for here.
Error: The Great British Public at work again.
Error: It's a mediocre, sentimental and safe song.
Error: Granted, it's not too bad, either.
Error: But can it stand up against ANYTHING by The Smiths (in particular "How Soon is Now?")
Error: or anything from the Stone Roses' first album?
Error: No, Because I'm not female and I'm not 10!
Error: Ok I like Robbie and Angels is a decent song.
Error: But it is no way the best song of the past 25 years!
Error: The shortlist wasn't great but him winning it is a joke!
Error: The success of Angels at this years Brits reflects poorly on the state of British music over the last 25 years.
Error: The British public are brainwashed by the corporate pulp that is presneted to them as cutting edge music and true talent is being sadly missed.
Error: Whilst Angels is a popular song it is not even the best song in Robbie's repertoire never mind best song of the last 25 years.
Error: I am a huge Robbie fan and love that song.
Error: But I think there are a lot more outstanding songs / music out there that influenced music today, unfortunately they were left out of the list.
Error: Have Radio 2 listeners even heard of Joy Division?
Error: A band who, through two albums, have had a bigger impact on music, and continue to do so, over the last 25 years than Robbie Williams ever will.
Error: There's not a song done by anyone with more emotion and feeling.
Error: Some people will adopt their slightly snobby stances, but Angels has hit home with a far larger audience than any other song.
Error: It should have been Joy Division.Those guys have played an influential part in shaping modern day music while Angels remains yet another pop song.
Error: I sincerely do not believe that in 25 years from now, the most influential artists will argue that Robbie Williams inspired their art in the way that the Byrds, the Beatles and Nick Drake have done for music today.
Error: I think its a brilliantly written song with different meanings to different people.
Error: There were other great songs in the category... but somebody had to win!
Error: Robbie was a deserved winner.
Error: I am astounded that such a second-rate record has beaten such a line up of amazing songs!
Error: it's a terrible song, voted for by the masses who don't have the brains to appreciate innovative and exciting music.
Error: The best song of the past 25 years?
Error: Come on, this is surely a joke?
Error: I think I need a long lie down...
Error: It just goes to show that the british public do not have a clue about good quality music when they pick Robbie Williams over the beautifully talented Kate Bush and Joy Division.
Error: I suppose it's confirmed one thing - the British public are consistently dull :- &lt;(

 No offence Robbie, but pleeease!
Error: There must be a thousand better songs than a formulated cheesy pop song for kids.
Error: No one agrees with this and quite frankly it is an embarassment to the integrity of British music, and a further nail in the coffin!
Error: I think Robbie deserves it, he has been the most iconic of any stars we have had in Britain since John Lennon and is an idol to millions worldwide.
Error: Anybody who says he doesn't deserve it is jealous of his success.
Error: The only real challenger was Queen but hey, Another One Bites the Dust!!
Error: Obviously all the Karaoke singers in the UK voted for it.
Error: If this is the best song of the last 25 years then the British Music industry is in trouble.
Error: Sure Robbie is talented and produces excellent material, but this is not the best record.
Error: A sad day for music

 It's not the type of music I normally like, but even as a diehard rock fan, I recognise that it is a good song and appelas to most people.
Error: That's why it has been voted best song of the last 25 years.
Error: Best song in 25 years?
Error: It's a nice, catchy, formulaic anthem that ticks all the boxes.
Error: I suppose it's just more evidence of how redundant the Brit Awards have become.
Error: Granted angels is a good song, however it really wasn't up against any other proper competition.
Error: The Queen's song was lackluster, and apart from Kate Bush, the other choices were pathetic!
Error: Also, why weren't the Stones there, David Bowie, etc, there are so many greater songs than Angels...I wonder if it was simply the fact that Robbie wasn't getting more awards so they had to make one up for him!
Error: Best song of the last 25 years?
Error: On the upside, at least it wasn't Bohemian Rhapsody, for which we should all be thankful.
Error: Angels is without doubt a great song but I really don't think it deserves the title of best song in 25 years.perhaps the vote had more to do with teenage opinion on Robbies' goodlooks than the actual song!!!
Error: Don't get me wrong, I'm not disputing his looks, but there are more deserved winners.
Error: Without Angels, Robbie Williams may well not be where he is now, and Britain would have been deprived of one of its most charismatic and talented performing artists.
Error: It has to be seen performed live, with 125,000 people singing along to be fully appreciated.
Error: I find it hard to believe that 'Angels' is the best we have to show for the past 25 years!
Error: I'm rapidly redifining 'best' in my own head now to mean 'most gratuitously played at weddings and funerals because people think it has deep meaning'.
Error: Blur, Oasis, Suede, Pulp... not only making fantastic songs but also making changes, doing something different.
Error: Why must 'best' always come down to most commercially popular?
Error: I've nothing against Robbie, I actually like his music, but how can this possibly be the best song from the last 25year?
Error: The Brits has proved to be nothing more than a bargaining tool between the pop moguls to boost band profiles and record sales.
Error: The same goes with the Scissor Sisters, I think this is a superb record and thoroughly deserves the newcomer award, but the album comes no where near U2's new record, neither are they in the same league.
Error: Once again there have been some baffling discisions made, they are not for artisic reasons, but for profit.
Error: Personally I find Angels by Robbie Williams to be one of the most irritating songs I have ever heard!
Error: It is a song that has united the generations and will continue to be played for many years to come.
Error: It's an absolute joke, however most of the original 25 were very poor choices as well.

   Unnamed: 0  ...                                               summ
0           0  ...  [The aim is to comment on international news e...
1           1  ...  [Asked if he would stand for the leadership ag...
2           2  ...  [Stuart Rose, head of M&S, said last year its ...
3           3  ...  [However Bwalya warned his side not to be too ...
4           4  ...  [Roger Federer became the first man since Mats...

[5 rows x 22 columns]

In [ ]:
testdata["summ"]= testdata["sent_token"].apply(lambda text:fuzzyimp(text))
testdata.head()

Error is : ['asks.']
Error is : ['why?']
Error is : ['tool.']
Error is : ['hope.']
Error is : ['improve."']
Error is : ['recalled.']
Error is : ['djs.']
Error is : ['added.']
Error is : ['terrible."']
Error is : ['exceptions.']
Error is : ['said.']
Error is : ['43,856.']
Error is : ['james.']
Error is : ['pity.']
Error is : ['theory.']
Error is : ['solutions.']
Error is : ['strange.']
Error is : ['nonsense.']
Error is : ['talented.']
Error: So what if Joss Stone won the Urban awards.
Error: Her music is great soul and surely that is under the 'Urban' banner?
Error: What if The Streets had won?
Error: Would people be whining because Mike Skinner is white...
Error: It seems that a lot of the fuss is about race where the real issue should be music and nothing else.
Error: Urban is PC version for saying black music.
Error: I'm not doubting Ms Stone's talent, but why didn't Jamelia or Lemar get a Brit?
Error: This reminds me of what happened to Craig David and Soul II Soul in the past, getting nominations are easy to get, but picking up a Brit seems to be the hardest thing.
Error: Refreshing to see people making reasonable, intelligent comments on any topic these days.
Error: You have said it: there is music you like and music you don't like - who cares what label you put on it?
Error: How can you have people like Dizzee Rascal up against Joss Stone?
Error: Joss Stone deserved to win an award for her talents, but I don't think it was very 'urban' of her to sing angels with Robbie Williams.
Error: Well almost all bands end up making music in London/Manchester etc.
Error: We live in cities and spend our working life in an urban environment; It therefore directly shapes what we write musically.
Error: Oasis originate from a city and characterise the urban life they know, therefore more than fit the term "urban" yet as they're a white rock band they won't be described as such.
Error: Joss Stone has a fantastic voice and great timing and delivery - what other reason do they need to award her the Brit?
Error: Urban is a crap, meaningless, politically correct and probably actually racist marketing term though.
Error: There's only two kinds of music: good and bad.
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error is : ['kamara.']
Error is : ['says.']
Error is : ['untrue.']
Error is : ['thundercats!!']
Error is : ['care!']
Error: Till then I'll have to make do with the Citreon C4 advert.
Error: I'd luv to see Willow the Wisp on the big screen but sadly without the late Kenneth Williams doing the voices it wouldnt be the same.
Error: And who remembers Trap Door voiced by the late Willie Rushden, superb children's programme.
Error: Could Morph hold his own in a big screen movie???
Error: At 34 I'm showing my age.
Error: :-)

 Noggin the Nog was one of the best children's programs.
Error: The problem with bringing it to the big screen is that no-one could approach Oliver Postgate's wonderful voices.
Error: The originals are good because they are of their time and the methods used are an integral part of the story.
Error: Just imagine what could be achieved by using CGI in a remake of Fingerbobs... the already disturbing hand antics of the bearded hippy, Yoffi could take on a whole new level with a more life-like Fingermouse

 Bob the Builder, Postman Pat and Fireman Sam together in an epic adventure of fire, post and bricks.
Error: In the ultimate struggle to save the women they love from the evil clowns, Krusty and Gobo.
Error: One puppet show that I personally would love to see made into a live action movie is Joe 90.
Error: It would be worth the price of admission alone to see the large screen version of Joe's car.
Error: Of course, Gerry Anderson's Supermarionation is a rich seam of material worthy of big-screen, big-budget action.
Error: It was only that Thunderbirds The Movie was targetted as a children't movie that really let it down.
Error: After all, the children that remember those shows with such affection are now the parents of children themselves.
Error: It's only because the people who were children when these programmes were first shown have grown up and are plundering their childhoods, isn't it?
Error: I'd hate to see Bagpuss with perfect animation - I love that 'done in a shed' clunkiness and you couldn't recreate the magic.
Error: Perhaps if the remakes were done in a 'Look Around You' mock-authentic style I might be interested ...

 Chorton And The Wheelies or Jamie And His Magic Torch; that would be mega!
Error: This re-gurgitation of old films and TV shows makes me angry - it is corporate laziness resting on the safety of other people's ideas, because it guarantees to bring in the $$$.
Error: The same can be said of modern day pop bands who release other peoples material, Will Young etc.
Error: The sad fact is nostalgia sells big bucks in the short-term.
Error: The fact that they will be forgotten in 6 months time is irrelevant (e.g.
Error: Starsky & Hutch) Hence, the market is saturated with this mindless drivel, but it can only be stopped if people stop buying it!
Error: I'm only 27 and don't remember the series from when it was on TV, but have the set on DVD and it's a classic.
Error: The fact it's so great comes from the fact that there were very few special effects involved and compared to today's stuff it looks amateurish.
Error: Thats the appeal though, it's so innocent (like Chorlton himself) and it would be a real shame if they did remake it.
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error in:
Error is : ['asks.']
Error is : ['confronted."']

   Unnamed: 0  ...                                               summ
0        1288  ...  [Instead Mr Blair will travel to key cities an...
1        1170  ...  [The South African archbishop said detentions ...
2        1388  ...  [Holmes starts 2005 with GB events\n \n Kelly ...
3        1109  ...  [Tory expert denies defeatism\n \n The Conserv...
4        1851  ...  [The MPAA said files found would not be passed...

[5 rows x 22 columns]

In [ ]:
traindata

      Unnamed: 0  ...                                               summ
0              0  ...  [The aim is to comment on international news e...
1              1  ...  [Hague 'given up' his PM ambition\n \n Former ...
2              2  ...  [M&S cuts prices by average of 24%\n \n Marks ...
3              3  ...  [Zambia confident and cautious\n \n Zambia's t...
4              4  ...  [Roger Federer became the first man since Mats...
...          ...  ...                                                ...
1775        1775  ...  [Kamal Nath, Commerce and Industry Minister, a...
1776        1776  ...  [The constitutional affairs secretary outlined...
1777        1777  ...  [Few realise that Westminster in effect has it...
1778        1778  ...  [Prutton poised for lengthy FA ban\n \n Southa...
1779        1779  ...  [Fry set for role in Hitchhiker's\n \n Actor S...

[1780 rows x 22 columns]

In [ ]:
#traindata[['summ']]
traindata[['Summary','summ']]

                                                Summary                                               summ
0     Dr Frasca said: "Political campaigns will cont...  [The aim is to comment on international news e...
1     Mr Hague became an MP at 27 and Leader of the ...  [Asked if he would stand for the leadership ag...
2     "We are bringing in ranges at new price points...  [Stuart Rose, head of M&S, said last year its ...
3     That victory for Angola also marked a first de...  [However Bwalya warned his side not to be too ...
4     Andy Roddick was the only player to put up any...  [Roger Federer became the first man since Mats...
...                                                 ...                                                ...
1775  He said, "No country can develop on the basis ...  [Analysts say improving India's infrastructure...
1776  Curfews and community service orders were othe...  [The constitutional affairs secretary outlined...
1777  But divorces are by no means the only document...  [Parliament's record of scandal\n \n In a lock...
1778  He was out of order but he knows that," said R...  [I can't condone what he's done., He was out o...
1779  Fry will provide the voice of The Guide, an el...  [Fry set for role in Hitchhiker's\n \n Actor S...

[1780 rows x 2 columns]

In [ ]:
testdata[['Summary','summ']]

                                               Summary                                               summ
0    Mr Milburn said the economy would take centre ...  [Instead Mr Blair will travel to key cities an...
1    The South African archbishop said detentions w...  [The South African archbishop said detentions ...
2    Holmes will make her first track appearance on...  [Holmes starts 2005 with GB events\n \n Kelly ...
3    Mr Howard appointed Mr Crosby as his elections...  [Tory expert denies defeatism\n \n The Conserv...
4    The Movie Association for America's (MPAA) fre...  [The MPAA said files found would not be passed...
..                                                 ...                                                ...
440  "But let us not forget two thirds of those wai...  [Welsh Health Minister Jane Hutt said no patie...
441  Former Labour leader Neil Kinnock has official...  [He will be known Baron Kinnock of Bedwellty -...
442  England coach Andy Robinson says English rugby...                                                 []
443  He clarified that he meant he would be in his ...  [Blunkett hints at election call\n \n Ex-Home ...
444  Federal Reserve chairman Alan Greenspan has wa...                                                 []

[445 rows x 2 columns]

In [ ]:
def sent_count(text):
  return len(text)

testdata["summ_count"]= testdata["summ"].apply(lambda text: sent_count(text))

In [ ]:
testdata.head()

   Unnamed: 0  ... summ_count
0        1288  ...         16
1        1170  ...          9
2        1388  ...          5
3        1109  ...          5
4        1851  ...          1

[5 rows x 24 columns]

In [ ]:
def listToString(text): 
    
    # initialize an empty string
    str1 = "" 
    
    # traverse in the string  
    for ele in text: 
        str1 += ele  
    
    # return string  
    return str1 


testdata["summ1"]= testdata["summ"].apply(lambda text:listToString(text))
testdata.head()

   Unnamed: 0  ...                                              summ1
0        1288  ...  Instead Mr Blair will travel to key cities and...
1        1170  ...  The South African archbishop said detentions w...
2        1388  ...  Holmes starts 2005 with GB events\n \n Kelly H...
3        1109  ...  Tory expert denies defeatism\n \n The Conserva...
4        1851  ...  The MPAA said files found would not be passed ...

[5 rows x 23 columns]

In [ ]:
traindata["summ1"]= traindata["summ"].apply(lambda text:listToString(text))
traindata.head()

   Unnamed: 0  ...                                              summ1
0           0  ...  The aim is to comment on international news ev...
1           1  ...  Asked if he would stand for the leadership aga...
2           2  ...  Stuart Rose, head of M&S, said last year its p...
3           3  ...  However Bwalya warned his side not to be too c...
4           4  ...  Roger Federer became the first man since Mats ...

[5 rows x 23 columns]

Evaluation

In [ ]:
!pip install rouge/requirements.txt
!pip install rouge-score
import numpy as np

def calc_rouge_scores(pred_summaries, gold_summaries, 
                                 keys=['rouge1', 'rougeL'], use_stemmer=True):
    #Calculate rouge scores
    from rouge_score import rouge_scorer
    scorer = rouge_scorer.RougeScorer(keys, use_stemmer= use_stemmer)
    n = len(pred_summaries)
    scores = [scorer.score(pred_summaries[j], gold_summaries[j]) for 
              j in range(n)] 
              
    #create dict
    dict_scores={}                                                            
    for key in keys:
        dict_scores.update({key: {}})
        
    #populate dict    
    for key in keys:
        
        precision_list = [scores[j][key][0] for j in range(len(scores))]
        recall_list = [scores[j][key][1] for j in range(len(scores))]
        f1_list = [scores[j][key][2] for j in range(len(scores))]

        precision = np.mean(precision_list)
        recall = np.mean(recall_list)
        f1 = np.mean(f1_list)
        
        dict_results = {'recall': recall, 'precision': precision, 'f1': f1}
        
        dict_scores[key] = dict_results
        
    return dict_scores

ERROR: Invalid requirement: 'rouge/requirements.txt'
Hint: It looks like a path. File 'rouge/requirements.txt' does not exist.
Collecting rouge-score
  Downloading https://files.pythonhosted.org/packages/1f/56/a81022436c08b9405a5247b71635394d44fe7e1dbedc4b28c740e09c2840/rouge_score-0.0.4-py2.py3-none-any.whl
Requirement already satisfied: absl-py in /usr/local/lib/python3.7/dist-packages (from rouge-score) (0.12.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (from rouge-score) (3.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from rouge-score) (1.19.5)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.7/dist-packages (from rouge-score) (1.15.0)
Requirement already satisfied: singledispatch in /usr/local/lib/python3.7/dist-packages (from nltk->rouge-score) (3.6.1)
Installing collected packages: rouge-score
Successfully installed rouge-score-0.0.4

In [ ]:
train_score=calc_rouge_scores(traindata['Summary'],traindata['summ1'])

In [ ]:
test_score=calc_rouge_scores(testdata['Summary'],testdata['summ1'])

In [ ]:
train_score

{'rouge1': {'f1': 0.40915824373559523,
  'precision': 0.5802837900764654,
  'recall': 0.3899472020949271},
 'rougeL': {'f1': 0.27147320331215075,
  'precision': 0.4102590357671459,
  'recall': 0.25215992619199545}}

In [ ]:
test_score

{'rouge1': {'f1': 0.40613583204419945,
  'precision': 0.5965621713014765,
  'recall': 0.379481750600277},
 'rougeL': {'f1': 0.27133718702419146,
  'precision': 0.4295955495238973,
  'recall': 0.24655069287973058}}

In [ ]:


#from nltk.translate.bleu_score import sentence_bleu
from nltk.translate.bleu_score import corpus_bleu

In [ ]:
train_bleuscore = corpus_bleu(traindata['Summary'],traindata['summ1'])

/usr/local/lib/python3.7/dist-packages/nltk/translate/bleu_score.py:490: UserWarning:
Corpus/Sentence contains 0 counts of 2-gram overlaps.
BLEU scores might be undesirable; use SmoothingFunction().
  warnings.warn(_msg)

In [ ]:
test_bleuscore=corpus_bleu(testdata['Summary'],testdata['summ1'])

/usr/local/lib/python3.7/dist-packages/nltk/translate/bleu_score.py:490: UserWarning:
Corpus/Sentence contains 0 counts of 2-gram overlaps.
BLEU scores might be undesirable; use SmoothingFunction().
  warnings.warn(_msg)

In [ ]:
train_bleuscore

0.4513462215360155

In [ ]:
test_bleuscore

0.45663483032129787