<a href="https://colab.research.google.com/github/varshaelza/Text-Summarization-Categorization/blob/main/TagMyNews_Classify.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
!pip install ipython-autotime
%load_ext autotime

Collecting ipython-autotime
  Downloading https://files.pythonhosted.org/packages/b4/c9/b413a24f759641bc27ef98c144b590023c8038dfb8a3f09e713e9dff12c1/ipython_autotime-0.3.1-py2.py3-none-any.whl
Requirement already satisfied: ipython in /usr/local/lib/python3.7/dist-packages (from ipython-autotime) (5.5.0)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (0.8.1)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (1.0.18)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (2.6.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (57.0.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (5.0.5)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (0.7.5)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (4.4.2)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.7/dist-packages (from ipython->ipython-autotime) (4.8.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->ipython-autotime) (0.2.5)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->ipython-autotime) (1.15.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.7/dist-packages (from traitlets>=4.2->ipython->ipython-autotime) (0.2.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect; sys_platform != "win32"->ipython->ipython-autotime) (0.7.0)
Installing collected packages: ipython-autotime
Successfully installed ipython-autotime-0.3.1
time: 171 Âµs (started: 2021-06-20 13:33:28 +00:00)

In [19]:
import pandas as pd
traindata = pd.read_csv('/content/drive/MyDrive/tagmynews/train_data.csv')
traindata.head()

   index1                                               news  type_id    type
0       0  court agrees to expedite n.f.l.'s appeal the d...        0  sports
1       1  no tsunami but fifa's corruption storm rages o...        0  sports
2       2  chung backs bin hammam in fifa presidential ra...        0  sports
3       3  rory mcilroy hangs on to slim lead at augusta ...        0  sports
4       4  figure skating: south korean skater stumbles, ...        0  sports

time: 434 ms (started: 2021-06-20 13:36:14 +00:00)

In [ ]:
testdata = pd.read_csv('/content/drive/MyDrive/tagmynews/tmntest.csv')
testdata.head()

   Unnamed: 0  index1  ... type_id           type
0           0    1176  ...       5  entertainment
1           1     959  ...       3       business
2           2     509  ...       1          world
3           3     759  ...       2             us
4           4     260  ...       0         sports

[5 rows x 5 columns]

time: 21.6 ms (started: 2021-06-20 10:01:23 +00:00)

In [20]:
#lowercase
traindata["news_lower"] = traindata["news"].str.lower()
#testdata["news_lower"] = testdata["news"].str.lower()

time: 9.22 ms (started: 2021-06-20 13:36:38 +00:00)

In [21]:
#no new line
traindata['news_wo_nltab'] = traindata['news_lower'].replace('\n','.', regex=True)
traindata['news_wo_nltab'] = traindata['news_wo_nltab'].replace('\t',' ', regex=True)
traindata['news_wo_nltab'] = traindata['news_wo_nltab'].replace(r'\.+', ".", regex=True)

#testdata['news_wo_nltab'] = testdata['news_lower'].replace('\n','.', regex=True)
#testdata['news_wo_nltab'] = testdata['news_wo_nltab'].replace('\t',' ', regex=True)
#testdata['news_wo_nltab'] = testdata['news_wo_nltab'].replace(r'\.+', ".", regex=True)

time: 28.1 ms (started: 2021-06-20 13:36:50 +00:00)

In [22]:
traindata.head()

   index1  ...                                      news_wo_nltab
0       0  ...  court agrees to expedite n.f.l.'s appeal the d...
1       1  ...  no tsunami but fifa's corruption storm rages o...
2       2  ...  chung backs bin hammam in fifa presidential ra...
3       3  ...  rory mcilroy hangs on to slim lead at augusta ...
4       4  ...  figure skating: south korean skater stumbles, ...

[5 rows x 6 columns]

time: 26 ms (started: 2021-06-20 13:36:54 +00:00)

In [ ]:
testdata.head()

   Unnamed: 0  ...                                      news_wo_nltab
0           0  ...  "book of mormon" leads with 14 tony nomination...
1           1  ...  at insider trial, defense attacks witness' dru...
2           2  ...  libya rebels show off arms captured at border ...
3           3  ...  after 'idol,' rap revue about college janelle ...
4           4  ...  nadal cruises past ljubicic into quarters rafa...

[5 rows x 7 columns]

time: 22.6 ms (started: 2021-06-20 10:02:17 +00:00)

In [23]:
#stopwords

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
print(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]
time: 712 ms (started: 2021-06-20 13:37:05 +00:00)

In [24]:
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])
traindata["news_wo_stop"] = traindata["news_wo_nltab"].apply(lambda text: remove_stopwords(text))
traindata.head()

   index1  ...                                       news_wo_stop
0       0  ...  court agrees expedite n.f.l.'s appeal decision...
1       1  ...  tsunami fifa's corruption storm rages though j...
2       2  ...  chung backs bin hammam fifa presidential race ...
3       3  ...  rory mcilroy hangs slim lead augusta britain's...
4       4  ...  figure skating: south korean skater stumbles, ...

[5 rows x 7 columns]

time: 39.9 ms (started: 2021-06-20 13:37:13 +00:00)

In [ ]:
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])
testdata["news_wo_stop"] = testdata["news_wo_nltab"].apply(lambda text: remove_stopwords(text))
testdata.head()

   Unnamed: 0  ...                                       news_wo_stop
0           0  ...  "book mormon" leads 14 tony nominations "the b...
1           1  ...  insider trial, defense attacks witness' drug u...
2           2  ...  libya rebels show arms captured border post ib...
3           3  ...  'idol,' rap revue college janelle bechdol, per...
4           4  ...  nadal cruises past ljubicic quarters rafael na...

[5 rows x 8 columns]

time: 25.7 ms (started: 2021-06-20 10:02:33 +00:00)

In [25]:
traindata['news_wo_no'] = traindata['news_wo_stop'].str.replace('(\d*\.\d+)|(\d+\.[0-9 ]+)|(\d)', '')
traindata.head()

   index1  ...                                         news_wo_no
0       0  ...  court agrees expedite n.f.l.'s appeal decision...
1       1  ...  tsunami fifa's corruption storm rages though j...
2       2  ...  chung backs bin hammam fifa presidential race ...
3       3  ...  rory mcilroy hangs slim lead augusta britain's...
4       4  ...  figure skating: south korean skater stumbles, ...

[5 rows x 8 columns]

time: 51.5 ms (started: 2021-06-20 13:37:21 +00:00)

In [ ]:
testdata['news_wo_no'] = testdata['news_wo_stop'].str.replace('(\d*\.\d+)|(\d+\.[0-9 ]+)|(\d)', '')
testdata.head()

   Unnamed: 0  ...                                         news_wo_no
0           0  ...  "book mormon" leads  tony nominations "the boo...
1           1  ...  insider trial, defense attacks witness' drug u...
2           2  ...  libya rebels show arms captured border post ib...
3           3  ...  'idol,' rap revue college janelle bechdol, per...
4           4  ...  nadal cruises past ljubicic quarters rafael na...

[5 rows x 9 columns]

time: 32.3 ms (started: 2021-06-20 10:02:44 +00:00)

Stemming

In [26]:
#porter stemmer
from nltk.stem import PorterStemmer

# Drop the two columns 

stemmer = PorterStemmer()
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

traindata["news_stem(porter)"] = traindata["news_wo_no"].apply(lambda text: stem_words(text))
traindata.head()

   index1  ...                                  news_stem(porter)
0       0  ...  court agre expedit n.f.l.' appeal decis mean r...
1       1  ...  tsunami fifa' corrupt storm rage though jack w...
2       2  ...  chung back bin hammam fifa presidenti race moh...
3       3  ...  rori mcilroy hang slim lead augusta britain' r...
4       4  ...  figur skating: south korean skater stumbles, s...

[5 rows x 9 columns]

time: 773 ms (started: 2021-06-20 13:37:27 +00:00)

In [ ]:
from nltk.stem import PorterStemmer

# Drop the two columns 

stemmer = PorterStemmer()
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

testdata["news_stem(porter)"] = testdata["news_wo_no"].apply(lambda text: stem_words(text))
testdata.head()

   Unnamed: 0  ...                                  news_stem(porter)
0           0  ...  "book mormon" lead toni nomin "the book mormon...
1           1  ...  insid trial, defens attack witness' drug use l...
2           2  ...  libya rebel show arm captur border post ibya b...
3           3  ...  'idol,' rap revu colleg janel bechdol, perfom ...
4           4  ...  nadal cruis past ljubic quarter rafael nadal s...

[5 rows x 10 columns]

time: 162 ms (started: 2021-06-20 10:02:54 +00:00)

In [27]:
#lancaster stemmer
from nltk.stem import LancasterStemmer

# Drop the two columns 

stemmer = LancasterStemmer()
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

traindata["news_stem(lancast)"] = traindata["news_wo_no"].apply(lambda text: stem_words(text))
traindata.head()

   index1  ...                                 news_stem(lancast)
0       0  ...  court agr expedit n.f.l.'s ap decid mean rul c...
1       1  ...  tsunam fifa's corrupt storm rag though jack wa...
2       2  ...  chung back bin hammam fif presid rac moham bin...
3       3  ...  rory mcilroy hang slim lead august britain's r...
4       4  ...  fig skating: sou kor skat stumbles, stil leads...

[5 rows x 10 columns]

time: 525 ms (started: 2021-06-20 13:37:37 +00:00)

In [ ]:
from nltk.stem import LancasterStemmer

# Drop the two columns 

stemmer = LancasterStemmer()
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

testdata["news_stem(lancast)"] = testdata["news_wo_no"].apply(lambda text: stem_words(text))
testdata.head()

   Unnamed: 0  ...                                 news_stem(lancast)
0           0  ...  "book mormon" lead tony nomin "the book mormon...
1           1  ...  insid trial, defens attack witness' drug us la...
2           2  ...  liby rebel show arm capt bord post iby bord - ...
3           3  ...  'idol,' rap revu colleg janel bechdol, perfom ...
4           4  ...  nad cru past ljub quart rafael nad spain adv f...

[5 rows x 11 columns]

time: 126 ms (started: 2021-06-20 10:03:05 +00:00)

In [28]:
#snowball stemmer
from nltk.stem.snowball import SnowballStemmer

# Drop the two columns 

stemmer = SnowballStemmer(language='english')
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

traindata["news_stem(snow)"] = traindata["news_wo_no"].apply(lambda text: stem_words(text))
traindata.head()

   index1  ...                                    news_stem(snow)
0       0  ...  court agre expedit n.f.l. appeal decis mean ru...
1       1  ...  tsunami fifa corrupt storm rage though jack wa...
2       2  ...  chung back bin hammam fifa presidenti race moh...
3       3  ...  rori mcilroy hang slim lead augusta britain ro...
4       4  ...  figur skating: south korean skater stumbles, s...

[5 rows x 11 columns]

time: 519 ms (started: 2021-06-20 13:37:44 +00:00)

In [ ]:
from nltk.stem.snowball import SnowballStemmer

# Drop the two columns 

stemmer = SnowballStemmer(language='english')
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

testdata["news_stem(snow)"] = testdata["news_wo_no"].apply(lambda text: stem_words(text))
testdata.head()

   Unnamed: 0  ...                                    news_stem(snow)
0           0  ...  "book mormon" lead toni nomin "the book mormon...
1           1  ...  insid trial, defens attack wit drug use lawyer...
2           2  ...  libya rebel show arm captur border post ibya b...
3           3  ...  idol, rap revu colleg janell bechdol, perfom j...
4           4  ...  nadal cruis past ljubic quarter rafael nadal s...

[5 rows x 12 columns]

time: 114 ms (started: 2021-06-20 10:03:15 +00:00)

In [30]:
#Regular Expression Stemmer

from nltk.stem import RegexpStemmer

# Drop the two columns 

stemmer = RegexpStemmer('ing$|s$|e$|able$', min=4)
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

traindata["news_stem(reg)"] = traindata["news_wo_no"].apply(lambda text: stem_words(text))
traindata.head()

   index1  ...                                     news_stem(reg)
0       0  ...  court agree expedit n.f.l.' appeal decision me...
1       1  ...  tsunami fifa' corruption storm rage though jac...
2       2  ...  chung back bin hammam fifa presidential rac mo...
3       3  ...  rory mcilroy hang slim lead augusta britain' r...
4       4  ...  figur skating: south korean skater stumbles, s...

[5 rows x 12 columns]

time: 63.2 ms (started: 2021-06-20 13:38:02 +00:00)

In [ ]:
from nltk.stem import RegexpStemmer

# Drop the two columns 

stemmer = RegexpStemmer('ing$|s$|e$|able$', min=4)
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

testdata["news_stem(reg)"] = testdata["news_wo_no"].apply(lambda text: stem_words(text))
testdata.head()

   Unnamed: 0  ...                                     news_stem(reg)
0           0  ...  "book mormon" lead tony nomination "th book mo...
1           1  ...  insider trial, defens attack witness' drug use...
2           2  ...  libya rebel show arm captured border post ibya...
3           3  ...  'idol,' rap revu colleg janell bechdol, perfom...
4           4  ...  nadal cruise past ljubicic quarter rafael nada...

[5 rows x 13 columns]

time: 38.8 ms (started: 2021-06-20 10:03:27 +00:00)

Lemmatization

In [31]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
time: 553 ms (started: 2021-06-20 13:38:11 +00:00)

In [32]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

traindata["news_lemmatize(wordnet)"] = traindata["news_wo_no"].apply(lambda text: lemmatize_words(text))
traindata.head()

   index1  ...                            news_lemmatize(wordnet)
0       0  ...  court agrees expedite n.f.l.'s appeal decision...
1       1  ...  tsunami fifa's corruption storm rage though ja...
2       2  ...  chung back bin hammam fifa presidential race m...
3       3  ...  rory mcilroy hang slim lead augusta britain's ...
4       4  ...  figure skating: south korean skater stumbles, ...

[5 rows x 13 columns]

time: 1.94 s (started: 2021-06-20 13:38:14 +00:00)

In [ ]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

testdata["news_lemmatize(wordnet)"] = testdata["news_wo_no"].apply(lambda text: lemmatize_words(text))
testdata.head()

   Unnamed: 0  ...                            news_lemmatize(wordnet)
0           0  ...  "book mormon" lead tony nomination "the book m...
1           1  ...  insider trial, defense attack witness' drug us...
2           2  ...  libya rebel show arm captured border post ibya...
3           3  ...  'idol,' rap revue college janelle bechdol, per...
4           4  ...  nadal cruise past ljubicic quarter rafael nada...

[5 rows x 14 columns]

time: 60.1 ms (started: 2021-06-20 10:03:44 +00:00)

In [33]:
#news_wo_punct(.)

import string
PUNCT_TO_REMOVE =  '''!()-[]{};:.'"\,<>/?@#$%^&*_~'''
def remove_punctuation(text):
    """custom function to remove the punctuation"""
    no_punct = ""
    for c in text:
      if c not in PUNCT_TO_REMOVE:
        no_punct = no_punct + c
      else:
        no_punct = no_punct + ' '
    return(no_punct)
traindata["news_wo_punct(.)"] = traindata["news_lemmatize(wordnet)"].apply(lambda text: remove_punctuation(text))
traindata.head()

   index1  ...                                   news_wo_punct(.)
0       0  ...  court agrees expedite n f l  s appeal decision...
1       1  ...  tsunami fifa s corruption storm rage though ja...
2       2  ...  chung back bin hammam fifa presidential race m...
3       3  ...  rory mcilroy hang slim lead augusta britain s ...
4       4  ...  figure skating  south korean skater stumbles  ...

[5 rows x 14 columns]

time: 67.9 ms (started: 2021-06-20 13:38:25 +00:00)

In [ ]:
import string
PUNCT_TO_REMOVE =  '''!()-[]{};:.'"\,<>/?@#$%^&*_~'''
def remove_punctuation(text):
    """custom function to remove the punctuation"""
    no_punct = ""
    for c in text:
      if c not in PUNCT_TO_REMOVE:
        no_punct = no_punct + c
      else:
        no_punct = no_punct + ' '
    return(no_punct)
testdata["news_wo_punct(.)"] = testdata["news_lemmatize(wordnet)"].apply(lambda text: remove_punctuation(text))
testdata.head()

   Unnamed: 0  ...                                   news_wo_punct(.)
0           0  ...   book mormon  lead tony nomination  the book m...
1           1  ...  insider trial  defense attack witness  drug us...
2           2  ...  libya rebel show arm captured border post ibya...
3           3  ...   idol   rap revue college janelle bechdol  per...
4           4  ...  nadal cruise past ljubicic quarter rafael nada...

[5 rows x 15 columns]

time: 37.6 ms (started: 2021-06-20 10:03:54 +00:00)

In [34]:
STOPWORDS = ['a' ,'b', 'c','d','e','f' ,'g' ,'h','i','j','k','l','m','n','o' ,'p' ,'q','r','s','t','u' ,'v' ,'w','x','y','z']
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])
traindata["news_wo_punct(.)&single"] = traindata["news_wo_punct(.)"].apply(lambda text: remove_stopwords(text))
traindata.head()

   index1  ...                            news_wo_punct(.)&single
0       0  ...  court agrees expedite appeal decision mean rul...
1       1  ...  tsunami fifa corruption storm rage though jack...
2       2  ...  chung back bin hammam fifa presidential race m...
3       3  ...  rory mcilroy hang slim lead augusta britain ro...
4       4  ...  figure skating south korean skater stumbles st...

[5 rows x 15 columns]

time: 59.1 ms (started: 2021-06-20 13:38:32 +00:00)

In [ ]:
STOPWORDS = ['a' ,'b', 'c','d','e','f' ,'g' ,'h','i','j','k','l','m','n','o' ,'p' ,'q','r','s','t','u' ,'v' ,'w','x','y','z']
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])
testdata["news_wo_punct(.)&single"] = testdata["news_wo_punct(.)"].apply(lambda text: remove_stopwords(text))
testdata.head()

   Unnamed: 0  ...                            news_wo_punct(.)&single
0           0  ...  book mormon lead tony nomination the book morm...
1           1  ...  insider trial defense attack witness drug use ...
2           2  ...  libya rebel show arm captured border post ibya...
3           3  ...  idol rap revue college janelle bechdol perfomi...
4           4  ...  nadal cruise past ljubicic quarter rafael nada...

[5 rows x 16 columns]

time: 40.2 ms (started: 2021-06-20 10:04:04 +00:00)

Tokenizer

In [35]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

time: 711 ms (started: 2021-06-20 13:38:41 +00:00)

In [36]:
traindata['news_tokenized(word)'] = traindata.apply(lambda row: nltk.word_tokenize(row['news_wo_punct(.)&single']), axis=1)
traindata.head()

   index1  ...                               news_tokenized(word)
0       0  ...  [court, agrees, expedite, appeal, decision, me...
1       1  ...  [tsunami, fifa, corruption, storm, rage, thoug...
2       2  ...  [chung, back, bin, hammam, fifa, presidential,...
3       3  ...  [rory, mcilroy, hang, slim, lead, augusta, bri...
4       4  ...  [figure, skating, south, korean, skater, stumb...

[5 rows x 16 columns]

time: 322 ms (started: 2021-06-20 13:38:45 +00:00)

In [ ]:
testdata['news_tokenized(word)'] = testdata.apply(lambda row: nltk.word_tokenize(row['news_wo_punct(.)&single']), axis=1)
testdata.head()

   Unnamed: 0  ...                               news_tokenized(word)
0           0  ...  [book, mormon, lead, tony, nomination, the, bo...
1           1  ...  [insider, trial, defense, attack, witness, dru...
2           2  ...  [libya, rebel, show, arm, captured, border, po...
3           3  ...  [idol, rap, revue, college, janelle, bechdol, ...
4           4  ...  [nadal, cruise, past, ljubicic, quarter, rafae...

[5 rows x 17 columns]

time: 76.7 ms (started: 2021-06-20 10:04:16 +00:00)

In [37]:
import string
PUNCT_TO_REMOVE =  '''!()-[]{};:'"\,<>/?@#$%^&*_~'''
def remove_punctuation(text):
    """custom function to remove the punctuation"""
    no_punct = ""
    for char in text:
      if char not in PUNCT_TO_REMOVE:
        no_punct = no_punct + char
      else:
        no_punct = no_punct + ' '
    return(no_punct)
traindata["news_wo_punct"] = traindata["news_lemmatize(wordnet)"].apply(lambda text: remove_punctuation(text))
traindata['news_wo_punct'] = traindata['news_wo_punct'].replace(r'\.+', ".", regex=True)
traindata.head()

   index1  ...                                      news_wo_punct
0       0  ...  court agrees expedite n.f.l. s appeal decision...
1       1  ...  tsunami fifa s corruption storm rage though ja...
2       2  ...  chung back bin hammam fifa presidential race m...
3       3  ...  rory mcilroy hang slim lead augusta britain s ...
4       4  ...  figure skating  south korean skater stumbles  ...

[5 rows x 17 columns]

time: 85.5 ms (started: 2021-06-20 13:38:52 +00:00)

In [ ]:
import string
PUNCT_TO_REMOVE =  '''!()-[]{};:'"\,<>/?@#$%^&*_~'''
def remove_punctuation(text):
    """custom function to remove the punctuation"""
    no_punct = ""
    for char in text:
      if char not in PUNCT_TO_REMOVE:
        no_punct = no_punct + char
      else:
        no_punct = no_punct + ' '
    return(no_punct)
testdata["news_wo_punct"] = testdata["news_lemmatize(wordnet)"].apply(lambda text: remove_punctuation(text))
testdata['news_wo_punct'] = testdata['news_wo_punct'].replace(r'\.+', ".", regex=True)
testdata.head()

   Unnamed: 0  ...                                      news_wo_punct
0           0  ...   book mormon  lead tony nomination  the book m...
1           1  ...  insider trial  defense attack witness  drug us...
2           2  ...  libya rebel show arm captured border post ibya...
3           3  ...   idol   rap revue college janelle bechdol  per...
4           4  ...  nadal cruise past ljubicic quarter rafael nada...

[5 rows x 18 columns]

time: 48 ms (started: 2021-06-20 10:04:29 +00:00)

In [38]:
STOPWORDS = ['a' ,'b', 'c','d','e','f' ,'g' ,'h','i','j','k','l','m','n','o' ,'p' ,'q','r','s','t','u' ,'v' ,'w','x','y','z']
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])
traindata["news_wo_punct&single"] = traindata["news_wo_punct"].apply(lambda text: remove_stopwords(text))
traindata.head()

   index1  ...                               news_wo_punct&single
0       0  ...  court agrees expedite n.f.l. appeal decision m...
1       1  ...  tsunami fifa corruption storm rage though jack...
2       2  ...  chung back bin hammam fifa presidential race m...
3       3  ...  rory mcilroy hang slim lead augusta britain ro...
4       4  ...  figure skating south korean skater stumbles st...

[5 rows x 18 columns]

time: 71.4 ms (started: 2021-06-20 13:39:00 +00:00)

In [ ]:
STOPWORDS = ['a' ,'b', 'c','d','e','f' ,'g' ,'h','i','j','k','l','m','n','o' ,'p' ,'q','r','s','t','u' ,'v' ,'w','x','y','z']
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])
testdata["news_wo_punct&single"] = testdata["news_wo_punct"].apply(lambda text: remove_stopwords(text))
testdata.head()

   Unnamed: 0  ...                               news_wo_punct&single
0           0  ...  book mormon lead tony nomination the book morm...
1           1  ...  insider trial defense attack witness drug use ...
2           2  ...  libya rebel show arm captured border post ibya...
3           3  ...  idol rap revue college janelle bechdol perfomi...
4           4  ...  nadal cruise past ljubicic quarter rafael nada...

[5 rows x 19 columns]

time: 46.4 ms (started: 2021-06-20 10:04:38 +00:00)

In [39]:
import nltk
nltk.download('punkt')
tk=nltk.RegexpTokenizer('[.]', gaps = True)
traindata['news_tokenized(reg)'] = traindata.apply(lambda row: tk.tokenize(row['news_wo_punct&single']), axis=1)
traindata.head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

   index1  ...                                news_tokenized(reg)
0       0  ...  [court agrees expedite n, f, l,  appeal decisi...
1       1  ...  [tsunami fifa corruption storm rage though jac...
2       2  ...  [chung back bin hammam fifa presidential race ...
3       3  ...  [rory mcilroy hang slim lead augusta britain r...
4       4  ...  [figure skating south korean skater stumbles s...

[5 rows x 19 columns]

time: 101 ms (started: 2021-06-20 13:39:07 +00:00)

In [ ]:
import nltk
nltk.download('punkt')
tk=nltk.RegexpTokenizer('[.]', gaps = True)
testdata['news_tokenized(reg)'] = testdata.apply(lambda row: tk.tokenize(row['news_wo_punct&single']), axis=1)
testdata.head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

   Unnamed: 0  ...                                news_tokenized(reg)
0           0  ...  [book mormon lead tony nomination the book mor...
1           1  ...  [insider trial defense attack witness drug use...
2           2  ...  [libya rebel show arm captured border post iby...
3           3  ...  [idol rap revue college janelle bechdol perfom...
4           4  ...  [nadal cruise past ljubicic quarter rafael nad...

[5 rows x 20 columns]

time: 44.7 ms (started: 2021-06-20 10:04:45 +00:00)

In [40]:
from nltk import sent_tokenize
nltk.download('punkt')
def tk(text):
  return sent_tokenize(text)
traindata['news_tokenized(sent)'] = traindata["news_wo_punct&single"].apply(lambda text: tk(text))
traindata.head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

   index1  ...                               news_tokenized(sent)
0       0  ...  [court agrees expedite n.f.l., appeal decision...
1       1  ...  [tsunami fifa corruption storm rage though jac...
2       2  ...  [chung back bin hammam fifa presidential race ...
3       3  ...  [rory mcilroy hang slim lead augusta britain r...
4       4  ...  [figure skating south korean skater stumbles s...

[5 rows x 20 columns]

time: 118 ms (started: 2021-06-20 13:39:14 +00:00)

In [ ]:
from nltk import sent_tokenize
nltk.download('punkt')
def tk(text):
  return sent_tokenize(text)
testdata['news_tokenized(sent)'] = testdata["news_wo_punct&single"].apply(lambda text: tk(text))
testdata.head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

   Unnamed: 0  ...                               news_tokenized(sent)
0           0  ...  [book mormon lead tony nomination the book mor...
1           1  ...  [insider trial defense attack witness drug use...
2           2  ...  [libya rebel show arm captured border post iby...
3           3  ...  [idol rap revue college janelle bechdol perfom...
4           4  ...  [nadal cruise past ljubicic quarter rafael nad...

[5 rows x 21 columns]

time: 59.4 ms (started: 2021-06-20 10:04:56 +00:00)

In [41]:
from nltk import word_tokenize
#nltk.download('punkt')
def tk(text):
  return word_tokenize(text)
traindata['news_tokenized(words)'] = traindata["news_wo_punct&single"].apply(lambda text: tk(text))

time: 283 ms (started: 2021-06-20 13:39:20 +00:00)

In [ ]:
from nltk import word_tokenize
#nltk.download('punkt')
def tk(text):
  return word_tokenize(text)
testdata['news_tokenized(words)'] = testdata["news_wo_punct&single"].apply(lambda text: tk(text))

time: 57.2 ms (started: 2021-06-20 10:05:54 +00:00)

In [42]:
def tk(text):
  while('.' in text):
    text.remove('.')
  return text
traindata['news_tokenized(reg)'] = traindata["news_tokenized(reg)"].apply(lambda text: tk(text))

time: 7.73 ms (started: 2021-06-20 13:39:23 +00:00)

In [ ]:
def tk(text):
  while('.' in text):
    text.remove('.')
  return text
testdata['news_tokenized(reg)'] = testdata["news_tokenized(reg)"].apply(lambda text: tk(text))

time: 3.35 ms (started: 2021-06-20 10:05:59 +00:00)

In [43]:
def tk(text):
  while(' ' in text):
    text.remove(' ')
  return text
traindata['news_tokenized(reg)'] = traindata["news_tokenized(reg)"].apply(lambda text: tk(text))

time: 9.13 ms (started: 2021-06-20 13:39:31 +00:00)

In [ ]:
def tk(text):
  while(' ' in text):
    text.remove(' ')
  return text
testdata['news_tokenized(reg)'] = testdata["news_tokenized(reg)"].apply(lambda text: tk(text))

time: 2.81 ms (started: 2021-06-20 10:06:06 +00:00)

In [44]:
def tk(text):
  while('.' in text):
    text.remove('.')
  return text
traindata['news_tokenized(sent)'] = traindata["news_tokenized(sent)"].apply(lambda text: tk(text))

time: 8.24 ms (started: 2021-06-20 13:39:34 +00:00)

In [ ]:
def tk(text):
  while('.' in text):
    text.remove('.')
  return text
testdata['news_tokenized(sent)'] = testdata["news_tokenized(sent)"].apply(lambda text: tk(text))

time: 2.36 ms (started: 2021-06-20 10:06:11 +00:00)

In [45]:
def tk(text):
  while(' ' in text):
    text.remove(' ')
  return text
traindata['news_tokenized(sent)'] = traindata["news_tokenized(sent)"].apply(lambda text: tk(text))

time: 7.95 ms (started: 2021-06-20 13:39:39 +00:00)

In [ ]:
def tk(text):
  while(' ' in text):
    text.remove(' ')
  return text
testdata['news_tokenized(sent)'] = testdata["news_tokenized(sent)"].apply(lambda text: tk(text))

time: 3.65 ms (started: 2021-06-20 10:06:17 +00:00)

In [46]:
def tk(text):
  while(' ' in text):
    text.remove(' ')
  return text
traindata['news_tokenized(words)'] = traindata["news_tokenized(words)"].apply(lambda text: tk(text))

time: 10.5 ms (started: 2021-06-20 13:39:48 +00:00)

In [ ]:
def tk(text):
  while(' ' in text):
    text.remove(' ')
  return text
testdata['news_tokenized(words)'] = testdata["news_tokenized(words)"].apply(lambda text: tk(text))

time: 2.72 ms (started: 2021-06-20 10:06:24 +00:00)

In [47]:
def tk(text):
  while('.' in text):
    text.remove('.')
  return text
traindata['news_tokenized(words)'] = traindata["news_tokenized(words)"].apply(lambda text: tk(text))

time: 6.84 ms (started: 2021-06-20 13:39:58 +00:00)

In [ ]:
def tk(text):
  while('.' in text):
    text.remove('.')
  return text
testdata['news_tokenized(words)'] = testdata["news_tokenized(words)"].apply(lambda text: tk(text))

time: 5.57 ms (started: 2021-06-20 10:06:29 +00:00)

In [48]:
df = pd.DataFrame(traindata)
df.to_csv('/content/drive/MyDrive/tagmynews/train_data1.csv')

time: 154 ms (started: 2021-06-20 13:40:35 +00:00)

In [49]:
traindata = pd.read_csv('/content/drive/MyDrive/tagmynews/train_data1.csv')
traindata.head()

   Unnamed: 0  ...                              news_tokenized(words)
0           0  ...  ['court', 'agrees', 'expedite', 'n.f.l', 'appe...
1           1  ...  ['tsunami', 'fifa', 'corruption', 'storm', 'ra...
2           2  ...  ['chung', 'back', 'bin', 'hammam', 'fifa', 'pr...
3           3  ...  ['rory', 'mcilroy', 'hang', 'slim', 'lead', 'a...
4           4  ...  ['figure', 'skating', 'south', 'korean', 'skat...

[5 rows x 22 columns]

time: 132 ms (started: 2021-06-20 13:40:50 +00:00)

In [ ]:
df = pd.DataFrame(testdata)
df.to_csv('/content/drive/MyDrive/tagmynews/tmntest.csv')

time: 30.6 ms (started: 2021-06-20 10:06:41 +00:00)

In [ ]:
testdata = pd.read_csv('/content/drive/MyDrive/tagmynews/tmntest.csv')
testdata.head()

   Unnamed: 0  ...                              news_tokenized(words)
0           0  ...  ['book', 'mormon', 'lead', 'tony', 'nomination...
1           1  ...  ['insider', 'trial', 'defense', 'attack', 'wit...
2           2  ...  ['libya', 'rebel', 'show', 'arm', 'captured', ...
3           3  ...  ['idol', 'rap', 'revue', 'college', 'janelle',...
4           4  ...  ['nadal', 'cruise', 'past', 'ljubicic', 'quart...

[5 rows x 23 columns]

time: 50.3 ms (started: 2021-06-20 10:06:45 +00:00)

# Under Sampling of dataset

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/tagmynews/tmntrain.csv')

time: 46.8 ms (started: 2021-06-20 10:12:55 +00:00)

In [ ]:
data

      Unnamed: 0  ...                              news_tokenized(words)
0              0  ...  ['anti', 'nuclear', 'german', 'protest', 'eve'...
1              1  ...  ['andre', 'ethier', 'extends', 'hit', 'streak'...
2              2  ...  ['rail', 'goldikova', 'racing', 'grande', 'dam...
3              3  ...  ['nasa', 'april', 'next', 'to', 'last', 'shutt...
4              4  ...  ['reporter', 'notebook', 'bizzy', 'buzzy', 'so...
...          ...  ...                                                ...
1141        1141  ...  ['cricket', 'cricket', 'legends', 'chance', 'l...
1142        1142  ...  ['iowa', 'swath', 'destruction', 'tornado', 't...
1143        1143  ...  ['pilot', 'survives', 'helicopter', 'crash', '...
1144        1144  ...  ['lenovo', 'see', 'pc', 'market', 'share', 'we...
1145        1145  ...  ['yankee', 'stop', 'hand', 'signal', 'mlb', 'i...

[1146 rows x 22 columns]

time: 38.3 ms (started: 2021-06-20 10:13:29 +00:00)

In [ ]:
import matplotlib.pyplot as plt
from collections import Counter
from sklearn.datasets import make_classification

counter = Counter(data['type'])
print(counter)

for type, _ in counter.items():
  row_ix = data[data['type'] == type]
  print(row_ix)

Counter({'business': 268, 'sports': 266, 'world': 224, 'us': 154, 'entertainment': 144, 'sci_tech': 90})
      Unnamed: 0  ...                              news_tokenized(words)
0              0  ...  ['anti', 'nuclear', 'german', 'protest', 'eve'...
5              5  ...  ['taliban', 'breach', 'afghan', 'prison', 'hun...
11            11  ...  ['egyptian', 'honor', 'activist', 'whose', 'de...
13            13  ...  ['somali', 'pirate', 'release', 'panama', 'fla...
15            15  ...  ['syrian', 'leader', 'brother', 'seen', 'enfor...
...          ...  ...                                                ...
1127        1127  ...  ['pressure', 'china', 'release', 'dissident', ...
1129        1129  ...  ['japanese', 'official', 'death', 'toll', 'lik...
1130        1130  ...  ['room', 'debate', 'taliban', 'jailbreak', 'af...
1133        1133  ...  ['crackdown', 'option', 'bahrain', 'sunni', 's...
1140        1140  ...  ['e.u', 'tie', 'future', 'aid', 'arab', 'world...

[224 rows x 22 columns]
      Unnamed: 0  ...                              news_tokenized(words)
1              1  ...  ['andre', 'ethier', 'extends', 'hit', 'streak'...
2              2  ...  ['rail', 'goldikova', 'racing', 'grande', 'dam...
9              9  ...  ['american', 'group', 'buy', 'three', 'time', ...
19            19  ...  ['gonzaga', 'hope', 'chic', 'women', 'underdog...
24            24  ...  ['connecticut', 'pittsburgh', 'walker', 'carry...
...          ...  ...                                                ...
1135        1135  ...  ['indycar', 'land', 'opportunity', 'woman', 'r...
1137        1137  ...  ['letter', 'editor', 'reader', 'sound', 'lates...
1138        1138  ...  ['photo', 'replay', 'may', 'view', 'day', 'spo...
1141        1141  ...  ['cricket', 'cricket', 'legends', 'chance', 'l...
1145        1145  ...  ['yankee', 'stop', 'hand', 'signal', 'mlb', 'i...

[266 rows x 22 columns]
      Unnamed: 0  ...                              news_tokenized(words)
3              3  ...  ['nasa', 'april', 'next', 'to', 'last', 'shutt...
4              4  ...  ['reporter', 'notebook', 'bizzy', 'buzzy', 'so...
10            10  ...  ['lg', 'expands', 'chip', 'supplier', 'away', ...
12            12  ...  ['australia', 'burping', 'cow', 'climate', 'fr...
25            25  ...  ['apple', 'nears', 'streaming', 'music', 'deal...
...          ...  ...                                                ...
1070        1070  ...  ['round', 'usual', 'c.e.o', 'year', 'testifyin...
1090        1090  ...  ['qihoo', 'share', 'double', 'nyse', 'debut', ...
1115        1115  ...  ['hop', 'bike', 'hopstop', 'equinox', 'say', '...
1117        1117  ...  ['exclusive', 'facebook', 'google', 'mull', 's...
1144        1144  ...  ['lenovo', 'see', 'pc', 'market', 'share', 'we...

[90 rows x 22 columns]
      Unnamed: 0  ...                              news_tokenized(words)
6              6  ...  ['palin', 'tour', 'campaign', 'prelude', 'publ...
18            18  ...  ['pittsburgh', 'medical', 'center', 'demotes',...
21            21  ...  ['judge', 'refuse', 'temporarily', 'block', 'i...
30            30  ...  ['obama', 'likely', 'announce', 're', 'electio...
47            47  ...  ['three', 'climber', 'rescued', 'top', 'mount'...
...          ...  ...                                                ...
1126        1126  ...  ['tornado', 'kill', 'least', 'one', 'man', 'ka...
1128        1128  ...  ['alabama', 'executes', 'man', 'killed', 'four...
1136        1136  ...  ['man', 'charged', 'allegedly', 'trying', 'ope...
1142        1142  ...  ['iowa', 'swath', 'destruction', 'tornado', 't...
1143        1143  ...  ['pilot', 'survives', 'helicopter', 'crash', '...

[154 rows x 22 columns]
      Unnamed: 0  ...                              news_tokenized(words)
7              7  ...  ['warner', 'music', 'nears', 'sale', 'access',...
8              8  ...  ['supreme', 'court', 'hears', 'argument', 'wal...
16            16  ...  ['morgan', 'stanley', 'trading', 'turnaround',...
17            17  ...  ['tnk', 'bp', 'partner', 'reject', 'bp', 'rosn...
22            22  ...  ['scientist', 'use', 'computer', 'read', 'huma...
...          ...  ...                                                ...
1108        1108  ...  ['saab', 'get', 'financing', 'lifeline', 'deal...
1109        1109  ...  ['mckinsey', 'uncomfortable', 'rajaratnam', 't...
1120        1120  ...  ['television', 'feed', 'urge', 'trade', 'week'...
1121        1121  ...  ['nasdaq', 'open', 'selling', 'amex', 'nyse', ...
1125        1125  ...  ['health', 'risk', 'fade', 'hormone', 'therapy...

[268 rows x 22 columns]
      Unnamed: 0  ...                              news_tokenized(words)
14            14  ...  ['jumping', 'broom', 'dust', 'familiar', 'them...
23            23  ...  ['britney', 'spear', 'confirms', 'surprise', '...
28            28  ...  ['mom', 'selena', 'gomez', 'series', 'justin',...
32            32  ...  ['social', 'worker', 'visit', 'carey', 'cannon...
52            52  ...  ['nbc', 'renews', 'office', 'parks', 'rec', 'c...
...          ...  ...                                                ...
1106        1106  ...  ['getting', 'party', 'mood', 'royal', 'wedding...
1110        1110  ...  ['discovery', 'bank', 'circus', 'swamp', 'new'...
1118        1118  ...  ['rio', 'roost', 'top', 'box', 'office', 'seco...
1134        1134  ...  ['critic', 'notebook', 'sequins', 'plume', 'fo...
1139        1139  ...  ['jennifer', 'hudson', 'writing', 'weight', 'l...

[144 rows x 22 columns]
time: 174 ms (started: 2021-06-20 10:15:51 +00:00)

In [ ]:
!pip install imbalanced-learn
import imblearn
print(imblearn.__version__)
from imblearn.under_sampling import RandomUnderSampler

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.7/dist-packages (0.4.3)
Requirement already satisfied: scipy>=0.13.3 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn) (1.4.1)
Requirement already satisfied: numpy>=1.8.2 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn) (1.19.5)
Requirement already satisfied: scikit-learn>=0.20 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn) (0.22.2.post1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20->imbalanced-learn) (1.0.1)

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)

0.4.3
time: 2.57 s (started: 2021-06-20 10:16:51 +00:00)

In [ ]:
import numpy as np

d = data['news_wo_punct&single'].values.tolist()
X=np.array(d).reshape(-1, 1)

time: 4.35 ms (started: 2021-06-20 10:17:21 +00:00)

In [ ]:
undersample = RandomUnderSampler(sampling_strategy='auto')
X_under, y_under = undersample.fit_resample(X, data['type'])

time: 7.47 ms (started: 2021-06-20 10:17:46 +00:00)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)

In [ ]:
print(Counter(y_under))
print(len(X_under))

Counter({'business': 90, 'entertainment': 90, 'sci_tech': 90, 'sports': 90, 'us': 90, 'world': 90})
540
time: 2.32 ms (started: 2021-06-20 10:18:04 +00:00)

In [ ]:
text = pd.DataFrame(data=X_under, columns=["news_wo_punct&single"])
text.head()

                                news_wo_punct&single
0  warm bath winter linked heart threat taking ho...
1  ireland say bank need billion euro ireland tri...
2  nasdaq negative japan nuclear fear amp nasdaq ...
3  scientist use computer read human thought hook...
4  mystery car ciao baby . car elegant machine se...

time: 13.6 ms (started: 2021-06-20 10:19:03 +00:00)

In [ ]:
Labels = pd.DataFrame(data=y_under, columns=["type"])
Labels.head()

       type
0  business
1  business
2  business
3  business
4  business

time: 12.3 ms (started: 2021-06-20 10:19:50 +00:00)

In [ ]:
frames = [text,Labels]
dataframe = pd.concat(frames,axis=1)
dataframe.head()

                                news_wo_punct&single      type
0  warm bath winter linked heart threat taking ho...  business
1  ireland say bank need billion euro ireland tri...  business
2  nasdaq negative japan nuclear fear amp nasdaq ...  business
3  scientist use computer read human thought hook...  business
4  mystery car ciao baby . car elegant machine se...  business

time: 14.1 ms (started: 2021-06-20 10:20:14 +00:00)

In [ ]:
len(Labels)

540

time: 2.45 ms (started: 2021-06-20 10:20:35 +00:00)

In [ ]:
df = pd.DataFrame(dataframe)
df.to_csv('/content/drive/MyDrive/tagmynews/tmnequitrain.csv')

time: 13.7 ms (started: 2021-06-20 10:22:38 +00:00)

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/tagmynews/tmnequitrain.csv')
data.head()

   Unnamed: 0                               news_wo_punct&single      type
0           0  warm bath winter linked heart threat taking ho...  business
1           1  ireland say bank need billion euro ireland tri...  business
2           2  nasdaq negative japan nuclear fear amp nasdaq ...  business
3           3  scientist use computer read human thought hook...  business
4           4  mystery car ciao baby . car elegant machine se...  business

time: 16.2 ms (started: 2021-06-20 10:23:41 +00:00)

In [ ]:
data

     Unnamed: 0                               news_wo_punct&single      type
0             0  warm bath winter linked heart threat taking ho...  business
1             1  ireland say bank need billion euro ireland tri...  business
2             2  nasdaq negative japan nuclear fear amp nasdaq ...  business
3             3  scientist use computer read human thought hook...  business
4             4  mystery car ciao baby . car elegant machine se...  business
..          ...                                                ...       ...
535         535  hidden workshop add libyan rebels arsenal clan...     world
536         536  special report find sponsor pay m.b.a. student...     world
537         537  assange wikileaks cable spurred arab uprising ...     world
538         538  e.u. tie future aid arab world democratic refo...     world
539         539  tunisia freeze gaddafi family assets governmen...     world

[540 rows x 3 columns]

time: 16.5 ms (started: 2021-06-20 10:24:46 +00:00)

# Classification

In [50]:
import pandas as pd
train = pd.read_csv('/content/drive/MyDrive/tagmynews/train_data1.csv')
#test = pd.read_csv('/content/drive/MyDrive/tagmynews/tmntest.csv')

time: 84.9 ms (started: 2021-06-20 13:41:46 +00:00)

In [51]:
train

      Unnamed: 0  ...                              news_tokenized(words)
0              0  ...  ['court', 'agrees', 'expedite', 'n.f.l', 'appe...
1              1  ...  ['tsunami', 'fifa', 'corruption', 'storm', 'ra...
2              2  ...  ['chung', 'back', 'bin', 'hammam', 'fifa', 'pr...
3              3  ...  ['rory', 'mcilroy', 'hang', 'slim', 'lead', 'a...
4              4  ...  ['figure', 'skating', 'south', 'korean', 'skat...
...          ...  ...                                                ...
1428        1428  ...  ['score', 'first', 'computer', 'musician', 'ev...
1429        1429  ...  ['apple', 'fan', 'line', 'buy', 'first', 'batc...
1430        1430  ...  ['nintendo', 'fun', 'addictive', 'pricey', 'fu...
1431        1431  ...  ['intel', 'unveils', 'laptop', 'include', 'tab...
1432        1432  ...  ['climb', 'ring', 'fight', 'night', 'champion'...

[1433 rows x 22 columns]

time: 60.4 ms (started: 2021-06-20 13:41:52 +00:00)

In [52]:
from sklearn import model_selection
Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(train['news_wo_punct&single'],train['type'],test_size=0.25)

time: 3.95 ms (started: 2021-06-20 13:42:04 +00:00)

In [53]:
from sklearn.feature_extraction.text import TfidfVectorizer
Tfidf_vect = TfidfVectorizer(max_features=5000)
Tfidf_vect.fit(train['news_wo_punct&single'])
Train_X_Tfidf = Tfidf_vect.transform(Train_X)
Test_X_Tfidf = Tfidf_vect.transform(Test_X)

time: 87.4 ms (started: 2021-06-20 13:42:08 +00:00)

In [54]:
print('TF-IDF output shape:', Train_X_Tfidf.shape)

TF-IDF output shape: (1074, 5000)
time: 1.27 ms (started: 2021-06-20 13:42:12 +00:00)

In [55]:
print('TF-IDF output shape:', Test_X_Tfidf.shape)

TF-IDF output shape: (359, 5000)
time: 1.13 ms (started: 2021-06-20 13:42:18 +00:00)

In [56]:
from sklearn.preprocessing import LabelEncoder
Encoder = LabelEncoder()
Train_Y = Encoder.fit_transform(Train_Y)
Test_Y = Encoder.fit_transform(Test_Y)

time: 3.45 ms (started: 2021-06-20 13:42:24 +00:00)

In [61]:
#svm

from sklearn import  naive_bayes, svm
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto')
SVM.fit(Train_X_Tfidf,Train_Y)
# predict the labels on validation dataset
predictions_SVM = SVM.predict(Test_X_Tfidf)
# Use accuracy_score function to get the accuracy
print("SVM Accuracy Score -> ",accuracy_score(predictions_SVM, Test_Y)*100)
print("SVM Precision Score -> ",precision_score(predictions_SVM, Test_Y, average='micro')*100)
print("SVM Recall Score -> ",recall_score(predictions_SVM, Test_Y, average='micro')*100)
print("SVM f1 Score -> ",f1_score(predictions_SVM, Test_Y, average='weighted')*100)

SVM Accuracy Score ->  75.20891364902506
SVM Precision Score ->  75.20891364902506
SVM Recall Score ->  75.20891364902506
SVM f1 Score ->  77.07678545942044
time: 482 ms (started: 2021-06-20 13:43:17 +00:00)

In [60]:
#naive bayes multinomial

Naive = naive_bayes.MultinomialNB()
Naive.fit(Train_X_Tfidf,Train_Y)
# predict the labels on validation dataset
predictions_NB = Naive.predict(Test_X_Tfidf)
# Use accuracy_score function to get the accuracy
print("Naive Bayes Accuracy Score -> ",accuracy_score(predictions_NB, Test_Y)*100)
print("Naive Bayes Precision Score -> ",precision_score(predictions_NB, Test_Y, average='micro')*100)
print("Naive Bayes Recall Score -> ",recall_score(predictions_NB, Test_Y, average='micro')*100)
print("Naive Bayes f1 Score -> ",f1_score(Test_Y, predictions_NB, average='weighted')*100)

Naive Bayes Accuracy Score ->  66.29526462395543
Naive Bayes Precision Score ->  66.29526462395543
Naive Bayes Recall Score ->  66.29526462395543
Naive Bayes f1 Score ->  59.51974083804023
time: 22.1 ms (started: 2021-06-20 13:43:13 +00:00)